### ISSUE TITLE
瀏覽器或應用程式可能有安全疑慮

### ISSUE THREAD

**Issue by RickyLeeeee** [max32002/tixcraft_bot#101]
透過 Google 登入帳戶，會顯示
```
目前無法登入帳戶

這個瀏覽器或應用程式可能有安全疑慮。 [瞭解詳情](https://support.google.com/accounts/answer/7675428?hl=zh-TW)
建議您改用其他瀏覽器。如果您目前已使用系統支援的瀏覽器，可以再試著登入帳戶。
```
且瀏覽器右上角會顯示 **錯誤**

昨天在拓元售票，今天在 Indievox 都遇到相同的問題，2023.09.04 版本也是一樣。

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/issues/3


RickyLeeeee ***@***.***> 於 2023年9月29日 週五 上午11:56 寫道：
