### ISSUE TITLE
IBON遇到新的UI無法自動輸入張數及驗證碼

### ISSUE THREAD

**Issue by alwww7** [max32002/tixcraft_bot#103]
使用場次: 鄭容和
遇到下圖介面無法自動選擇張數及輸入驗證碼
![螢幕擷取畫面 2023-10-05 191431](https://github.com/max32002/tixcraft_bot/assets/126540775/e2c3aa5f-c181-46ca-b3d8-3e4a2f5aef88)

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/commit/df0b8af7322c19661557e81e37594ac725a7ea83
