### ISSUE TITLE
0907年代售票系統 自動輸入

### ISSUE THREAD

**Issue by a3504411** [max32002/tixcraft_bot#105]
版主您好

請問最新的年代售票是否無法自動輸入張數及驗證碼

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/commit/6a73d90432cdf4ab98ef48fb81542f36052c17eb

**Comment by a3504411** [comment]
版主您好

剛剛測試新版 只有自動輸入驗證碼，並不會自動輸入張數及勾選不連續位置
