### ISSUE TITLE
09-13最新版本年代系統張數及驗證碼會同時卡住

### ISSUE THREAD

**Issue by alwww7** [max32002/tixcraft_bot#107]
最新版本的程式測試年代系統，發現在電腦選位時有機率會出現只有輸入數量後就直接送出，不會輸入驗證碼，且機率蠻高的
測試場次:浪漫的「妥協」-陳宏寬與ESO
![image](https://github.com/max32002/tixcraft_bot/assets/126540775/69b380be-aa13-411f-8af7-cb4b0272690c)

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/commit/964483766498b2290438fbbdd2fc5f1854283fcc
