### ISSUE TITLE
2023.09.15版本 hkticketing(firefox, edge, safari)出現問題

### ISSUE THREAD

**Issue by TryBot1234** [max32002/tixcraft_bot#108]
網站hkticketing
Firefox
不使用自動登錄: refresh了3x-4x次後會白畫面停止運作
自動登錄: 白畫面無法進入 https://premier.hkticketing.com/Secure/ShowLogin.aspx

edge 及safari出現下列錯誤字句無法運作
create web driver object fail @_@;
web driver not accessible!

請問如何解決？謝謝

另外: Chrome & Brave 功能運作正常!^^

**Comment by max32002** [comment]
無解, 因為 undetected-chromedriver 暫時無法套用在 chrome 以外, 但理論上應該可以. 參考看看:
https://github.com/ultrafunkamsterdam/undetected-chromedriver

**Comment by max32002** [comment]
edge 及safari, 需要手動下載 web driver, 參考看看:
https://max-everyday.com/2018/03/tixcraft-bot/
理論上, edge 似乎有機會可以套用 undetected-chromedriver,

**Comment by TryBot1234** [comment]
作者短時間就回覆我了，很開心，謝謝

**Comment by TryBot1234** [comment]
> edge 及safari, 需要手動下載 web driver, 參考看看: https://max-everyday.com/2018/03/tixcraft-bot/ 理論上, edge 似乎有機會可以套用 undetected-chromedriver,

Edge確實解決了，謝謝，另外想問safari的web driver在那可以下載？參考網址上找不到，再次謝謝

**Comment by max32002** [comment]
MaxBot 最後一個分頁有放超連結。

TryBot1234 ***@***.***> 於 2023年10月12日 週四 下午10:32 寫道：

**Comment by TryBot1234** [comment]
謝謝回覆。MaxBot最後一頁只看到
- Chrome Driver
- Firefox Driver
- Edge Driver
還是找不到safari driver.....>,<

**Comment by max32002** [comment]
問題似乎解決了, 如果還有其他問題, 歡迎再開issue. 謝謝.

**Comment by TryBot1234** [comment]
max32002大大牛逼
