### ISSUE TITLE
hkticketing 未能自動短時間REFRESH 等待頁面

### ISSUE THREAD

**Issue by JonT1221** [max32002/tixcraft_bot#109]
hkticketing 未能自動短時間REFRESH 等待頁面
![image](https://github.com/max32002/tixcraft_bot/assets/145976605/0240c67e-0546-40b3-8709-88627d935747)

**Comment by max32002** [comment]
目前似乎無法測試.

**Comment by dbpanicvin** [comment]
同遇到 抢PG One加场的时候出现过此问题

**Comment by max32002** [comment]
2024-01-10 MaxBot Plus 擴充功能 刷hkticketing
擴充功能的Options裡有選項可以調整重刷之間的間隔.
擴充功能可以直接在github 上下載zip 檔後, 在 chrome://extensions/ 的開發者模式下 load unpacked extension 到 chrome 瀏覽器中. 
* 使用說明: https://max-everyday.com/2018/03/tixcraft-bot/
* 檔案下載: https://github.com/max32002/tixcraft_bot/releases
* YouTube: https://youtu.be/zOzFYJsqWME
