### ISSUE TITLE
新版跑firefox會有問題

### ISSUE THREAD

**Issue by s08216** [max32002/tixcraft_bot#11]
瀏覽器用firefox，貌似會有找不到路徑的error

**Comment by max32002** [comment]
請問使用 (2023-03-04) 的版本, 會有找不到路徑的error嗎?

**Comment by max32002** [comment]
請移除 Firefox 並重新安裝在系統預設的 C:\ 裡的路徑下, 如果是 macOS, 請把程式移到 Application 目錄裡, 還有再遇到問題的話, 請再開新的 issue.
