### ISSUE TITLE
遠大的序號部分不會填寫

### ISSUE THREAD

**Issue by ShuoYu1026** [max32002/tixcraft_bot#111]
![擷取](https://github.com/max32002/tixcraft_bot/assets/109022855/5fa33544-f841-46b6-a2a6-108bec286600)

https://ticketplus.com.tw/order/302afbc05769b5bb67e93359608bdc4e/98246e60c6db2bbcfcd166c9a07c4f4b

**Comment by max32002** [comment]
05ba4e43f4a0f32ee8ca4208f274bed75653c468
