### ISSUE TITLE
使用Mac m1 2023.09.15的版本python執行時卡在 No module named 'distutils'

### ISSUE THREAD

**Issue by lukay1004** [max32002/tixcraft_bot#112]
python是最新版本，也有下載chrome

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/issues/104

lukay1004 ***@***.***> 於 2023年10月21日 週六 下午9:52 寫道：

**Comment by max32002** [comment]
未來也許會解決, 暫時請先降低python 12 為 python 10, 謝謝.
