### ISSUE TITLE
遠大驗證碼目前會擋大小寫

### ISSUE THREAD

**Issue by wei3639783** [max32002/tixcraft_bot#114]
剛測試發現說現在一定要符合大小寫才給過
不過看驗證碼圖片都是小寫的樣子

**Comment by max32002** [comment]
測試, 功能無誤, 你可換一台Windows 電腦試看看.

**Comment by ShuoYu1026** [comment]
我剛剛用三台Windows電腦測試都跟他回報的出現同一個情況

**Comment by max32002** [comment]
> 我剛剛用三台Windows電腦測試 都跟他回報一樣情況

那一個他?

**Comment by ShuoYu1026** [comment]
> > 我剛剛用三台Windows電腦測試都告訴他返回同樣的情況
> 
> 那個他？

機器人會輸入大寫導致驗證碼輸入錯誤 然後被強制登出

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/commit/f6ffc53eb9e84580e0508c858b9e45f8d837a38d
