### ISSUE TITLE
10.02版 遠大不會自動到驗證碼欄位

### ISSUE THREAD

**Issue by Rscathac** [max32002/tixcraft_bot#117]
遠大選位子張數都沒問題
但選完張數不會自動跳到驗證碼的欄位
command line 會跳出 find verify textbox fail
有試過拓元沒這個問題

裝置是apple M2 不確定是否有影響？

**Comment by max32002** [comment]
強烈建議, 不要使用 apple M1/M2 來搶票, 因為驗證碼功能不支援, 請參考這篇的回答:
https://github.com/max32002/tixcraft_bot/issues/82
