### ISSUE TITLE
adblock 有點問題

### ISSUE THREAD

**Issue by sam0324sam** [max32002/tixcraft_bot#118]
https://ticketplus.com.tw/activity/c752489ad3e922cbd8943deccdd22696
這邊會跳個廣告

我嘗試加入adblock規則，這是我在開啟的搶票視窗添加的，但是寫到BOT上無效
ticketplus.com.tw##.text-center.pa-5.v-card.v-sheet.theme--light
ticketplus.com.tw##.primary-1.float-btn.v-btn.v-btn--fab.v-btn--icon.v-btn--round.theme--light.v-size--small.white--text
ticketplus.com.tw##.v-overlay__scrim

問題有兩個
1. 勾選瀏覽器擴充功能後，adblock的視窗會導致需要先手動關閉 https://welcome.adblockplus.org/ 的頁面
2. 我新增規則上去不生效

再麻煩大大了

**Comment by sam0324sam** [comment]
確定了，預設的adb規則不會像影片那樣更新上去

**Comment by lufat** [comment]
打開搶票網站廣告跳出後就一直重複刷新網頁，請問有什麼解決辦法嗎

**Comment by sam0324sam** [comment]
> 打開搶票網站廣告跳出後就一直重複刷新網頁，請問有什麼解決辦法嗎

不管他 沒差
還有代搶 yoasobi 轉賣的都沒父母

**Comment by lufat** [comment]
跟我一樣為了yoasobi而來XD
只能用同樣的方法對付他們

**Comment by lufat** [comment]
開賣前就進去讓他刷業面嗎

**Comment by max32002** [comment]
MaxBot 2023-10-11: 遠大,自動按"好玩其他活動"
https://youtu.be/-CazfZFvoh0
