### ISSUE TITLE
無法猜測驗證碼

### ISSUE THREAD

**Issue by Lin19941001** [max32002/tixcraft_bot#119]
Max大您好，我更新最新版本的機器人在拓元網站出現無法猜測驗證碼的狀況
Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=118.0.5993.117)
Stacktrace:
0   chromedriver                        0x000000010e8b8e08 chromedriver + 5025288
1   chromedriver                        0x000000010e8afc23 chromedriver + 4987939
2   chromedriver                        0x000000010e451e67 chromedriver + 409191
3   chromedriver                        0x000000010e425be4 chromedriver + 228324
4   chromedriver                        0x000000010e4cdebf chromedriver + 917183
5   chromedriver                        0x000000010e4e3b56 chromedriver + 1006422
6   chromedriver                        0x000000010e4c82b3 chromedriver + 893619
7   chromedriver                        0x000000010e492eb9 chromedriver + 675513
8   chromedriver                        0x000000010e4940ee chromedriver + 680174
9   chromedriver                        0x000000010e87a819 chromedriver + 4769817
10  chromedriver                        0x000000010e87f893 chromedriver + 4790419
11  chromedriver                        0x000000010e88666e chromedriver + 4818542
12  chromedriver                        0x000000010e8805bd chromedriver + 4793789
13  chromedriver                        0x000000010e85298c chromedriver + 4606348
14  chromedriver                        0x000000010e89eb78 chromedriver + 4918136
15  chromedriver                        0x000000010e89ed30 chromedriver + 4918576
16  chromedriver                        0x000000010e8af85e chromedriver + 4986974
17  libsystem_pthread.dylib             0x00007ff81bd5e1d3 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff81bd59bd3 thread_start + 15
find TicketForm_agree fail
Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=118.0.5993.117)
Stacktrace:
0   chromedriver                        0x000000010e8b8e08 chromedriver + 5025288
1   chromedriver                        0x000000010e8afc23 chromedriver + 4987939
2   chromedriver                        0x000000010e451e67 chromedriver + 409191
3   chromedriver                        0x000000010e425be4 chromedriver + 228324
4   chromedriver                        0x000000010e4cdebf chromedriver + 917183
5   chromedriver                        0x000000010e4e3b56 chromedriver + 1006422
6   chromedriver                        0x000000010e4c82b3 chromedriver + 893619
7   chromedriver                        0x000000010e492eb9 chromedriver + 675513
8   chromedriver                        0x000000010e4940ee chromedriver + 680174
9   chromedriver                        0x000000010e87a819 chromedriver + 4769817
10  chromedriver                        0x000000010e87f893 chromedriver + 4790419
11  chromedriver                        0x000000010e88666e chromedriver + 4818542
12  chromedriver                        0x000000010e8805bd chromedriver + 4793789
13  chromedriver                        0x000000010e85298c chromedriver + 4606348
14  chromedriver                        0x000000010e89eb78 chromedriver + 4918136
15  chromedriver                        0x000000010e89ed30 chromedriver + 4918576
16  chromedriver                        0x000000010e8af85e chromedriver + 4986974
17  libsystem_pthread.dylib             0x00007ff81bd5e1d3 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff81bd59bd3 thread_start + 15
find select fail
find form-select fail
NoSuchWindowException at this url: 
get_log: Unable to evaluate script: no such window: target window already closed
from unknown error: web view not found

**Comment by max32002** [comment]
target window already closed, 由MaxBot 所開出的搶票視窗被關閉, 所以程式無法接續進行網頁的自動化控制.
