### ISSUE TITLE
KKTIX 籃球門票

### ISSUE THREAD

**Issue by a3504411** [max32002/tixcraft_bot#12]
今天試了一下好像不支援籃球門票的選位置

**Comment by max32002** [comment]
請問, 詳細的需求是什麼? 現在 (2023-03-04) 的版本, 可以選擇位置嗎?

**Comment by max32002** [comment]
如果還有再遇到不支援籃球門票的選位置, 請再開新的 issue, 並附近測試用的活動名稱, 謝謝.
