### ISSUE TITLE
ticketmaster.sg无法选择区域和座位

### ISSUE THREAD

**Issue by kentzh1** [max32002/tixcraft_bot#125]
项目地址：https://ticketmaster.sg/activity/detail/24_edsheeran
无论设定还是不设定关键词，都提醒find verify textbox fail，无法选择座位，以前有出现过类似情况，需要辅助点击区域，才能继续流程，不知道出现了什么问题。

![image](https://github.com/max32002/tixcraft_bot/assets/67768011/37362aa2-d845-4812-80c8-85c0a264e186)

**Comment by dbpanicvin** [comment]
有可能是要你选中黄色或者紫色里面的字段 例如PB1 PC1 PB2 PC2

**Comment by kentzh1** [comment]
> 有可能是要你选中黄色或者紫色里面的字段 例如PB1 PC1 PB2 PC2

我不设置关键词，也不会自动选择可用的区域

**Comment by max32002** [comment]
由於 已 Soldout, 無法測試, 用其他已開賣的場測來說, 下面這場在 2023-11-01 測試結果是正常的. 
https://ticketmaster.sg/ticket/area/24_melodies/1285

您需要的說明: [MaxBot]請問新加坡的 ticketmaster 怎麼輸入選區呢?
https://max-everyday.com/2023/10/ticketmaster-area-auto-select/

**Comment by kentzh1** [comment]
> 由於 已 Soldout, 無法測試, 用其他已開賣的場測來說, 下面這場在 2023-11-01 測試結果是正常的. https://ticketmaster.sg/ticket/area/24_melodies/1285
> 
> 您需要的說明: [MaxBot]請問新加坡的 ticketmaster 怎麼輸入選區呢? https://max-everyday.com/2023/10/ticketmaster-area-auto-select/
你发的这个链接，是没问题，你可以测试一下我发的这个链接，它不会按照设定的区域抢购，比如我设置CAT1 C，它会自动锁定A或者是其它区域，Ed Sheeran是无论设置与否，都不会自动点击，需要辅助点击。
https://ticketmaster.sg/activity/detail/23_leejunho

**Comment by max32002** [comment]
關鍵字下 “CAT1 C”, 希望可選到右下角的黃色 C 區域, 實際上卻是選到右上角黃色 A 區, 為什麼?

因為以關鍵字 “CAT1 C”, 來說是要同時符合”CAT1″ 與 “C”, 由於程式的預設排序沒有修改過的話, 是 “from top to bottom”, 意思是遇到第一個符合的就不再往下去檢查,

“CAT1 A”, 是有同時符合 “CAT1” 與 “C” 關鍵字.

如果是要選擇到右下角的黃色 C 區域, 可以直接使用關鍵字 “cat1c” 或調整你的排序值.

**Comment by max32002** [comment]
詳細說明, 參考看看:
[MaxBot]請問新加坡的 ticketmaster 怎麼輸入選區呢?
https://max-everyday.com/2023/10/ticketmaster-area-auto-select/
