### ISSUE TITLE
执行网址没内容，max不运行

### ISSUE THREAD

**Issue by kentzh1** [max32002/tixcraft_bot#126]
max，不好意思，使用中我又遇到了问题,在运行过程中，执行阶段里面，执行网址为空白，然后命令窗口就出现如图，无法正常运作，不知道我什么地方出现了问题

![image](https://github.com/max32002/tixcraft_bot/assets/67768011/b3ea4ec8-27ea-469e-8d73-f03be4fa685a)

**Comment by max32002** [comment]
測試 MaxBot 2023-11-01 使用 chrome / brave 瀏覽器, 一切都正常. 

測試用活動:
https://ticketmaster.sg/activity/game/23_mansuang
