### ISSUE TITLE
ticketmaster.sg广告弹窗

### ISSUE THREAD

**Issue by kentzh1** [max32002/tixcraft_bot#127]
Max你好，sg好像更改了网站，我和朋友在运行max时，都会如图广告弹窗，我没开启拦截广告插件，也删除了过滤广告规则，依然无法取消和点击，不知道你进入sg是否有此类问题？
![image](https://github.com/max32002/tixcraft_bot/assets/67768011/da50e79b-37a9-4168-95a8-8e6f82656604)

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/commit/3aa3f7960528e160a94b6d64f27a99f45c79da02
download 2023-11-02
