### ISSUE TITLE
Tag 20221114 Issue

### ISSUE THREAD

**Issue by HPJ1996** [max32002/tixcraft_bot#13]
1. 有使用到新套件 PIL `pip-reg.txt` 中 需加入 Pillow
2. 找不到 maxbot_logo2_single.png

**Comment by max32002** [comment]
你好專業哦，感謝。

**Comment by HPJ1996** [comment]
還是要感謝 Max 大大提供程式

**Comment by max32002** [comment]
暫時修改為 GUI 介面內建支援的奇怪格式的 PPM, 先移掉 Pillow 等到之後有必要時，再來加入。也感謝你的回報 issue.
