### ISSUE TITLE
ticketmaster.sg隐藏图片模式会触发弹窗bug

### ISSUE THREAD

**Issue by kentzh1** [max32002/tixcraft_bot#130]
Max您好，在sg运行过程中，隐藏部分图片选项，会触发无法链接网站的弹窗，导致不能继续购票流程，测试关闭无图模式会解决这个问题； 包括在无票情况下，网页持续刷新，也会触发这个弹窗，请问是什么原因导致？是刷新过快被识别了吗？
![image](https://github.com/max32002/tixcraft_bot/assets/67768011/278bc76e-afec-48ac-ad3c-a74a096ce82a)

**Comment by max32002** [comment]
請下載 2023-11-08 版, 如果還有遇到問題, 請附上有問題的場次, 謝謝.
