### ISSUE TITLE
在調用FIREFOX 時會出現URL Exception: 'WebDriver' object has no attribute 'execute_cdp_cmd'

### ISSUE THREAD

**Issue by JonT1221** [max32002/tixcraft_bot#131]
![image](https://github.com/max32002/tixcraft_bot/assets/145976605/0678dec0-474a-4355-8d17-a3dbbdd482e1)

**Comment by max32002** [comment]
cdp即Chrome DevTools Protocal, 
請下載  2023-11-09 版. 
https://github.com/max32002/tixcraft_bot/commit/98cc2a74ba69cccd55b19e2635976c7375928668

**Comment by JonT1221** [comment]
got it
