### ISSUE TITLE
hkticketing 區域關鍵字

### ISSUE THREAD

**Issue by TryBot1234** [max32002/tixcraft_bot#133]
就算區域關鍵字我輸入了  "HK$2299","HK$899"
但都會自動搶購 Best available any price category from HK$899
能選擇個別價錢搶購嗎？ 謝謝大大

![Price](https://github.com/max32002/tixcraft_bot/assets/147679397/b209bdd1-1b19-4ff0-b1fd-2a3965caedac)

**Comment by max32002** [comment]
2023-11-16, 以  MaxBot 2023-11-13 版, 測試以下場次, 設關鍵字 "680", 結果正常.

如果還有遇到問題, 請附上使用中的版本, 與測試中的場次, 謝謝.
