### ISSUE TITLE
[拓元] 無法進行Google OAuth登入

### ISSUE THREAD

**Issue by iita71737** [max32002/tixcraft_bot#138]
經由Setting啟動並至拓元後，
目前無法成功進行官網的Google第三方登入。

**Comment by max32002** [comment]
經測試99%的人無法登入。已移除該功能。


DanLin ***@***.***> 於 2023年11月22日 週三 下午11:05 寫道：

**Comment by iita71737** [comment]
想請教一下，目前最新版本，拓 元 能使用嗎？
剛剛用最新版本開拓 元也無法正常顯示><
