### ISSUE TITLE
MacOS PIL問題

### ISSUE THREAD

**Issue by hua1215** [max32002/tixcraft_bot#141]
您好，2023-11-19版本仍然出現以下訊息：

`ImportError: cannot import name '_imaging' from 'PIL'`

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/commit/38b7ba39f5c9a8d513ebc473b3ac07016da32b6b

解法有2個, 
解法1: 在 macOS 裡開啟 Terminal App 後, 貼上並執行下列的指令:
python3 -m pip install Pillow

或是使用解法2, 下載 2023-11-20 版本.
