### ISSUE TITLE
拓元facebook登入有問題

### ISSUE THREAD

**Issue by sb9495** [max32002/tixcraft_bot#144]
如標題, 拓元會員登入輸入帳密後就會出現問題無法繼續搶票如下圖
請問要如何解決?
![image](https://github.com/max32002/tixcraft_bot/assets/152413202/2e3e38a4-c32f-4827-b4b4-2e78d79be752)
![image](https://github.com/max32002/tixcraft_bot/assets/152413202/64a3bbba-3f7b-419b-bbf9-80cbc9e68cb7)
使用的是最新版本chrome_tixcraft.20231123_Win10_Win11.zip

**Comment by max32002** [comment]
https://max-everyday.com/2023/11/maxbot-troubleshooting/#block_facebook

sb9495 ***@***.***> 於 2023年11月29日 週三 下午11:01 寫道：
