### ISSUE TITLE
interpark_bot 无法绕过cloudflare

### ISSUE THREAD

**Issue by holly21461** [max32002/tixcraft_bot#145]
Max大您好，看到interpark机器人说无法通过cloudflare的问题，想请问您还会继续更新替换掉selenium吗？谢谢

**Comment by max32002** [comment]
你issue, 開錯專案了:
https://max-everyday.com/2023/08/interpark-bot/

還沒決定, 花時間應該就可以解, 因為是有確定可以過的解法, 還沒找到去花時間的動力.
