### ISSUE TITLE
遠大無法進入購票頁面

### ISSUE THREAD

**Issue by ooyamaP** [max32002/tixcraft_bot#146]
就算是已經開始販售的票，也會一直刷新網頁，不會點進去購票頁面。
顯示如下:
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
not found date-time-position
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
not found date-time-position
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.

**Comment by Yo2449** [comment]
而且有機率會被退回首頁
empty date item, delay 0.2 to retry.
empty date item, delay 0.2 to retry.
try to click button fail, force click by js.

**Comment by max32002** [comment]
請試看看 2023-12-02 版本, 
如果還有遇到問題, 請附上可以測試的場次, 謝謝.

**Comment by progress7614** [comment]
![螢幕擷取畫面 2023-12-09 204743](https://github.com/max32002/tixcraft_bot/assets/148855848/5a6a2206-c482-4b6f-806c-751c435217ec)
![螢幕擷取畫面 2023-12-09 204818](https://github.com/max32002/tixcraft_bot/assets/148855848/47700c57-58d3-48cc-a986-3bcf80d2c7ec)
以上為供測試的場次
懇請作者幫忙

**Comment by max32002** [comment]
請問, 你有用 2023-12-02 版去刷過這些場次嗎? 
我的測試結果是符合預期。

**Comment by progress7614** [comment]
非常感謝作者的回覆，目前沒有這個問題了
