### ISSUE TITLE
遠大驗證碼無法自動輸入

### ISSUE THREAD

**Issue by mm10079** [max32002/tixcraft_bot#148]
嘗試了兩場演唱會，沒有自動輸入驗證碼
版本：2023-12-05 /2023-12-01
看了最新的版本沒有相關的更新，開了這個回饋

**Comment by max32002** [comment]
目前版本是 2023-12-12...

**Comment by max32002** [comment]
請下載 2023-12-13 版, 如果還有遇到問題, 再開新的issue, 謝謝。
