### ISSUE TITLE
帳號問題

### ISSUE THREAD

**Issue by a3504411** [max32002/tixcraft_bot#149]
MAX 大您好
目前有和您一樣使用虛擬機，但有發現假設個資不是真的再開賣當下好像無法成功購票(儘管過程都是順利的)，不知道MAX大有遇到類似的情況嗎

**Comment by max32002** [comment]
請問，其他已開賣場次，可否購票？

Jacky Lin ***@***.***> 於 2023年12月19日 週二 下午2:39 寫道：

**Comment by a3504411** [comment]
都可以，假設12:00開賣，就這個開賣當下買不到，但是朋友用台灣電腦(超鳥的那種)有買到

**Comment by max32002** [comment]
沒遇過..., 建議您用真實資料多創點小帳來搶. 
參考這則影片:
https://youtu.be/8M5LwSZNDX0

**Comment by max32002** [comment]
請先用其他已開賣的場次測試看看.

如果還有遇到這個問題, 請再開 issue,  謝謝.
