### ISSUE TITLE
建議新增 Adblock Plus

### ISSUE THREAD

**Issue by bluefatcat1993** [max32002/tixcraft_bot#15]
建議新增 Adblock Plus
https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb

並且 Adblock Plus 設定過濾
tixcraft.com###topAlert
tixcraft.com##.col-md-7.col-xs-12.mg-top
tixcraft.com##.topBar.alert-box.emergency
tixcraft.com##.footer.clearfix
tixcraft.com##.row.process-wizard.process-wizard-info
tixcraft.com##.nav-line
tixcraft.com##.page-info.row.line-btm.mg-0

**Comment by max32002** [comment]
https://youtu.be/Atujl8MPHQI
