### ISSUE TITLE
遠大刷新問題

### ISSUE THREAD

**Issue by dolphin88615** [max32002/tixcraft_bot#152]
max大您好，跟您請教一下
遠大現在刷新會出現2種網頁，其中一種會導致網頁卡住，不會重新整理
如果區域選random的話，會一直選擇不同區直到選完所有區才會重新整理

以Ado這場為例
https://ticketplus.com.tw/order/54fdee72c71c18cc2b694801e11e77cd/f0f79e5625bc6c00e54cbe419bbde9fe

重新整理會出現2種網頁
a.有顯示剩餘票數 -> 正常刷新
![1](https://github.com/max32002/tixcraft_bot/assets/154688675/3200d5cf-a1ff-4d1f-8896-afd76c67728d)
b.沒顯示剩餘票數 -> 會先選完所有區再重新整理
![2](https://github.com/max32002/tixcraft_bot/assets/154688675/963b6ddc-2f60-40fe-816c-3a3ebe92db8c)

請教一下Max大有辦法處理這個問題嗎，感謝您

**Comment by max32002** [comment]
2023-12-21 版應該修正了這一個問題, 
請再幫忙測試其他瞬間由尚未開賣切成開賣的場次, 謝謝.
