### ISSUE TITLE
刷新卡住自動登出影響其他瀏覽器

### ISSUE THREAD

**Issue by canele4games** [max32002/tixcraft_bot#154]
使用chrome_tixcraft 1220版本
在遠大ticketplus 平台 刷新ado的票
網址如下
[](https://ticketplus.com.tw/order/54fdee72c71c18cc2b694801e11e77cd/f0f79e5625bc6c00e54cbe419bbde9fe)
刷新一小段時間後會卡住 只有中間灰色圓圈一直轉
![image](https://github.com/max32002/tixcraft_bot/assets/155558627/072f2378-0065-4c9e-9e44-2e9ae9040cb4)
重新整理會跳出登入畫面，但輸入帳號密碼無法登入 
![image](https://github.com/max32002/tixcraft_bot/assets/155558627/e6c59e9e-dc2b-4247-abe1-7b4aa6a0fb08)

甚至會影響到其他視窗
新開一個瀏覽器視窗輸入網址
也會一直重整無法跑出頁面
再次重啟程式 再登入畫面時 會一直跳刷新
![image](https://github.com/max32002/tixcraft_bot/assets/155558627/18b251bd-a325-4b9f-b8e1-b061c16b6bff)
![image](https://github.com/max32002/tixcraft_bot/assets/155558627/dfb99bb6-8e1a-45fe-990b-5323c17eff55)

**Comment by max32002** [comment]
你真厲害，居然還保留後面那頁的網址，理論上從 /acitivity/ 那一頁應該是沒有超連結可以到後面 /order/ 這頁。

**Comment by max32002** [comment]
44 看 2023-12-21 版。

**Comment by canele4games** [comment]
還是有一樣的問題
oder 那頁跑一跑就會卡住，然後整個ticket plus, activity, 和 order 這三頁都進不去，就算改用edge 開一樣
重新開maxbot就會變成卡在登入輸入帳密的畫面進不去，點擊空白處也會一直跳登入輸入帳密的框框

由於連帶影響到除了chrome的瀏覽器，在想是否可能是電腦的哪個指令或是程序需要關掉，還是是官方對ip位置的暫時封禁，不知道其他人目前是否有類似的問題。

**Comment by max32002** [comment]
有 Wu 姓網友幫忙測試, 刷 2分鐘左右就會被系統登出. 解法,請下載 2023-12-23 版, 在 chrome 擴充功能裡, MaxBot Extension 選項 "Add reandom delay for auto reload" 打勾:
![chrome_2024-01-05_11-42_7f](https://github.com/max32002/tixcraft_bot/assets/4498233/22731dc0-6ba8-466f-bf73-06926acf0109)
