### ISSUE TITLE
kktix中不能自动填充资格码 手动填充后不能自动重试下一步

### ISSUE THREAD

**Issue by dbpanicvin** [max32002/tixcraft_bot#158]
以SJ香港预售为例:https://kktix.com/events/sjlss2024/registrations/new
![微信截图_20240111154231](https://github.com/max32002/tixcraft_bot/assets/22132033/e24b04b8-b2ee-4ad9-9ba4-f1fef3ea840f)
在使用者自定字典填入资格码后 进入选票阶段不能自动填充
在手动填充资格码后 bot不能自动重试按下下一步

**Comment by yunimm** [comment]
@max32002 請問max大大，這個issue在最新版本有被解決了嗎？

**Comment by max32002** [comment]
KKIX 加購粉絲福利
https://youtu.be/Hc2wW_sWiAo

-----= 以下為火星文, 可以略過 =----
這個功能, 其實古時候就有做好, 但是在某一個版本, 我腦筋打結, 在把原本用 python 寫的程式, 搬到  chrome extension, 誤以為有寫 javascript 的自動輸入在 chrome extension 裡, 實際上, 沒寫, 所以這個功能又持續無法使用.
