### ISSUE TITLE
No matching distribution found for python-chromedriver-autoinstaller-max

### ISSUE THREAD

**Issue by cauli123** [max32002/tixcraft_bot#159]
安裝套件時會找不到這個包
是換名字了嗎?
https://github.com/max32002/chromedriver-autoinstaller-max

chromedriver-autoinstaller-max VS python-chromedriver-autoinstaller-max

$ python3 -m pip install -r pip-req.txt 
ERROR: Could not find a version that satisfies the requirement python-chromedriver-autoinstaller-max (from versions: none)
ERROR: No matching distribution found for python-chromedriver-autoinstaller-max

$python3 --version
Python 3.10.12

$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"

**Comment by cauli123** [comment]
遺失chromedriver_autoinstaller_max 沒有chromedriver 會導致瀏覽器無法開啟

$ python3 settings.py
setting app version: MaxBot (2024.01.05)
python version: 3.10.12
platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
run button pressed.
save config result: True
execute in shell mode.
try python
try python3
Traceback (most recent call last):
  File "/home/myaccount/project/tixcraft_bot/chrome_tixcraft.py", line 22, in <module>
    import chromedriver_autoinstaller_max
ModuleNotFoundError: No module named 'chromedriver_autoinstaller_max'

**Comment by max32002** [comment]
感謝您的回報. 

fix typo. 
https://github.com/max32002/tixcraft_bot/commit/734eef79031500893681c4391c73d2fa179c6436

**Comment by chuanxd** [comment]
@max32002 我使用最新的 commit 一樣會有這問題

**Comment by max32002** [comment]
python3 -m pip install -r pip-req.txt

**Comment by max32002** [comment]
我今天在新的 VM 環境下也有遇到相同問題, 解法是, 把 terminal 關掉, 重開一次 terminal, 先用 python -m pip list 確定 package 是有被安裝的, 這時候, 輸入 python 按 enter 進入 python 之後, 
手動輸入 import chromedriver_autoinstaller_max
這時候, 如果沒有出現錯誤訊息就成功了, 回去再跑MaxBot 就會正常.

**Comment by chuanxd** [comment]
@max32002 

我分享一下我後來解法：
我的環境有多個 python 版本

原本是用 python 3.10 pip install，後來改用 python 3.9 pip install 後解決這個問題

給其他人遇到時參考


OS: macOS
