### ISSUE TITLE
kktix 不規則 數字驗證碼 有辦法自動填寫嗎

### ISSUE THREAD

**Issue by jlcfr025** [max32002/tixcraft_bot#160]
![Screenshot 2024-01-12 111544](https://github.com/max32002/tixcraft_bot/assets/125731526/adf07afa-3b14-479b-850c-f9ee2146334a)

**Comment by max32002** [comment]
請問你用主程式的版本去跑，有自動輸入嗎？

**Comment by max32002** [comment]
2023-12-10 就已支援, 參考看看影片:

KKTIX 搶車票
https://youtu.be/csUJ6kRSynY
