### ISSUE TITLE
驗證碼

### ISSUE THREAD

**Issue by YangInu** [max32002/tixcraft_bot#163]
請問出現這個
2 0 2 4 - 0 1 - 1 5   1 1 : 0 2 : 1 7 . 8 0 4 8 2 4 7   [ W : o n n x r u n t i m e : D e f a u l t ,   o n n x r u n t i m e _ p y b i n d _ s t a t e . c c : 1 9 8 3   o n n x r u n t i m e : : p y t h o n : : C r e a t e I n f e r e n c e P y b i n d S t a t e M o d u l e ]   I n i t   p r o v i d e r   b r i d g e   f a i l e d .
 maxbot app version: MaxBot (2024.01.06)
python version: 3.10.11
platform: Windows-10-10.0.19045-SP0
homepage: https://tixcraft.com/activity/detail/24_gx
browser: chrome
ticket_number: 2
webdriver_type: undetected_chromedriver
ChromeDriver exist: C:\Users\USER\Desktop\chrome_tixcraft\webdriver\chromedriver.exe
goto url: https://tixcraft.com/activity/detail/24_gx
ocr_answer: lnne
ocr_answer: xfgu
oh no not again, WebDriverException
WebDriverException: Alert Text: 您所輸入的驗證碼不正確，請重新輸入
Message: unexpected alert open: {Alert text : 您所輸入的驗證碼不正確，請重新輸入}
  (Session info: chrome=120.0.6099.217)
Stacktrace:
        GetHandleVerifier [0x008C6EE3+174339]
        (No symbol) [0x007F0A51]
        (No symbol) [0x00506FF6]
        (No symbol) [0x0050F678]
        (No symbol) [0x00512676]
        (No symbol) [0x004F93BB]
        (No symbol) [0x0050F22D]
        (No symbol) [0x0056A05B]
        (No symbol) [0x00556DA6]
        (No symbol) [0x00531034]
        (No symbol) [0x00531F8D]
        GetHandleVerifier [0x00964B1C+820540]
        sqlite3_dbdata_init [0x00A253EE+653550]
        sqlite3_dbdata_init [0x00A24E09+652041]
        sqlite3_dbdata_init [0x00A197CC+605388]
        sqlite3_dbdata_init [0x00A25D9B+656027]
        (No symbol) [0x007FFE6C]
        (No symbol) [0x007F83B8]
        (No symbol) [0x007F84DD]
        (No symbol) [0x007E5818]
        BaseThreadInitThunk [0x779AFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77C07C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77C07C3E+238]

只是驗證碼辨識錯誤嗎?
重複一直讓他跑直到成功嗎?

**Comment by max32002** [comment]
下載看看 2024-01-08 版,
