### ISSUE TITLE
chrome driver error

### ISSUE THREAD

**Issue by mingnain** [max32002/tixcraft_bot#166]
我下載了chrome driver linux,並放到webdriver資料夾中 有偵測到ChromeDriver exist: webdriver/chromedriver
但會跑出Binary Location Must be a String 然後chrome driver就被刪除了

python3  chrome_tixcraft.py
maxbot app version: MaxBot (2024.01.12)
python version: 3.9.12
platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
homepage: https://tixcraft.com
browser: chrome
ticket_number: 2
webdriver_type: undetected_chromedriver
ChromeDriver exist: webdriver/chromedriver
Binary Location Must be a String
Deleting exist and download ChromeDriver again.
No chrome executable found on PATH
WebDriver object is still None..., try download by uc.
Binary Location Must be a String
create web drive object by undetected_chromedriver fail!
建議您自行下載 ChromeDriver 到 webdriver 的資料夾下
you need manually download ChromeDriver to webdriver folder.
create web driver object fail @_@;
web driver not accessible!

**Comment by max32002** [comment]
題外話，想知情道你這台機器，使用 curl https://tixcraft.com 顯示的是正常html網頁內容，還是IP被擋掉。

**Comment by mingnain** [comment]
因為看到虛擬機好像比較快，所以才想說用虛擬機執行

**Comment by max32002** [comment]
你的這個問題, 在WSL2環境裡, 並沒有安裝 WSL2 對應的chrome瀏覽器在Window虛擬機中, 所以顯示訊息:
`No chrome executable found on PATH`

你所下載的 webdriver 之所以會被刪掉, 是因為啟動失敗, 所以python 的腳本會刪除已經下載好的, 而且是剛才挑戰去使用的 webdriver, 刪掉後會開始自動下載 webdriver.
