### ISSUE TITLE
maxbot plus增加自动验证码功能

### ISSUE THREAD

**Issue by kentzh1** [max32002/tixcraft_bot#168]
希望maxbot plus增加自动验证码功能，SG好像打开maxbot plus，会导致地图和选择按钮不可见

**Comment by max32002** [comment]
MaxBot Plus 1.0.6 擴充功能 for ticktmaster.sg
需要手動的部份: 選區域(area),
程式自動的部份: (依序為) 選日期, 輸入張數(Quantity), 選擇電腦選位(Best Available), 輸入OCR的驗證碼, 打勾同意 Agree, 送出 Submit.
* 使用說明: https://max-everyday.com/2018/03/tixcraft-bot/
* 檔案下載: https://github.com/max32002/tixcraft_bot/
* YouTube: https://youtu.be/V8S_E7ayAGU
