### ISSUE TITLE
ModuleNotFoundError: No module named 'chromedriver_autoinstaller_max'

### ISSUE THREAD

**Issue by leoho0722** [max32002/tixcraft_bot#169]
您好，我是透過 git clone master branch 的原始碼來執行的
Python 是透過 Homebrew 安裝，版本為 Python 3.10.13
在執行 ```python3.10 setting.py``` 前有先安裝套件 ```python3.10 -m pip install -r pip-req.txt```
透過 GUI 點擊搶票按鈕時，Terminal print 出「ModuleNotFoundError: No module named 'chromedriver_autoinstaller_max'」

無論是使用 Intel based 或是 Apple Silicon based 的 Mac 都有遇到此問題

### Intel based Mac
![Intel based Mac](https://github.com/max32002/tixcraft_bot/assets/73574800/0833cf94-110c-49d5-967b-abc9490c9ccf)

### Apple Silicon Mac
![Apple Silicon based Mac](https://github.com/max32002/tixcraft_bot/assets/73574800/1950d36c-df3d-45aa-a4e7-e1885e09469f)

再麻煩您解答了，感謝

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/issues/159

**Comment by max32002** [comment]
解法很簡單，開啟 terminal 輸入指令：
`python -m pip install chromedriver-autoinstaller-max`

**Comment by leoho0722** [comment]
後來我是直接修改 ```settings.py``` 的第 1202 行，將原先的 ```python3``` 改成我的 ```python3.10```
這樣就可以透過搶票按鈕來執行了

感謝您解答

**Comment by chuanxd** [comment]
@leoho0722  你這個方法是最佳解沒錯，因為程式裡預設使用 `python` 如果沒有 `python` 指令就會換成使用 `python3` 指令
