### ISSUE TITLE
Run Settings.exe 有error

### ISSUE THREAD

**Issue by dadahaha99** [max32002/tixcraft_bot#17]
在run setting 時出現error
![error](https://user-images.githubusercontent.com/122029855/210794568-5f30c622-38d4-4513-b2e7-77c706dd176e.jpg)
請問可以怎樣辦?

但在run tixcraft時則可執行, 郤只能執行預設的網址, 例如最新版本是cityline, 只可打開cityline購票, 因為行不到setting, 所以改不了網址, 去不了urbix或kktix, 請幫忙

**Comment by max32002** [comment]
不要把目錄放在 Program Files 目錄下就行了。

**Comment by dadahaha99** [comment]
Thanks!
