### ISSUE TITLE
Ubuntu 20.04 will occurred PIL error

### ISSUE THREAD

**Issue by KevinYang1108** [max32002/tixcraft_bot#170]
Dear Max, My OS was Ubuntu 20.04, and will occurred bellow PIL error, my Python version was 3.8.10

Is there anything should i do? I have try reinstall Pillow but it doesn't work

port: 16888  is in used.
setting app version: MaxBot (2024.01.15)
python version: 3.8.10
platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.29
run button pressed.
save config result: True
execute in shell mode.
try python
Traceback (most recent call last):
  File "chrome_tixcraft.py", line 37, in <module>
    from NonBrowser import NonBrowser
  File "/home/kevin/Desktop/ticket robot/MaxBot_20240115/MaxBot.app/Contents/Resources/NonBrowser.py", line 6, in <module>
    from PIL import Image
  File "/home/kevin/Desktop/ticket robot/MaxBot_20240115/MaxBot.app/Contents/Resources/PIL/Image.py", line 84, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/home/kevin/Desktop/ticket robot/MaxBot_20240115/MaxBot.app/Contents/Resources/PIL/__init__.py)

**Comment by max32002** [comment]
1: MaxBot.app is for  macOS only not for ubuntu. 

2: please use git clone or download the zip file from github to run the python script.

see this tutorial:
https://max-everyday.com/2023/11/buy-ticket-by-vm/

demo video (run on rocky linux 8):
「2023年第30屆亞洲棒球錦標賽」搶票分享(有搶到)
https://youtu.be/8M5LwSZNDX0
