### ISSUE TITLE
MacOS PIL問題

### ISSUE THREAD

**Issue by hua1215** [max32002/tixcraft_bot#171]
您好 最新版本仍出現mportError: cannot import name '_imaging' from 'PIL'

執行python3 -m pip install Pillow還是一樣。

**Comment by max32002** [comment]
可能是您執行 settings.py 與 python3 chrome_tixcraft.py 這2個指令的版本不同。

**Comment by max32002** [comment]
請參考這部影片的解法, 
透過原始碼執行MaxBot教學影片： https://youtu.be/HpVG91j0lbI

Step 1: 取得source code:

`git clone https://github.com/max32002/tixcraft_bot.git`

Step 2: 進入 clone 的資料夾: tixcraft_bot:

`cd tixcraft_bot `

Step 3: 安裝第三方套件:

`python3 -m pip install -r pip-req.txt`

Step 4: 執行設定界面主桯式:

`python3 settings.py`

如果遇到MaxBot 改版, 請重新操作上面4個步驟一次, 即可取得新的版本.

如果MaxBot 沒改版, 第二次要再執行的話, 使用 Step 2 + Step 4, 這2行指令, 就可以執行 MaxBot.

如果你是 ARM CPU 應該會在 Step 3 就顯示錯誤訊息, 解法: https://github.com/max32002/tixcraft_bot/issues/82#issuecomment-1878986084
