### ISSUE TITLE
 驗證碼問題

### ISSUE THREAD

**Issue by annannn123** [max32002/tixcraft_bot#172]
MAX大大您好
目前電腦為非M1M2版本的MAC，環境如下圖
<img width="578" alt="截圖 2024-02-01 上午3 13 47" src="https://github.com/max32002/tixcraft_bot/assets/158338013/b9a5a9fc-6d55-4b1e-9b8f-a26d5284cf03">

下載最新版本MaxBot APP也出現 ImportError: cannot import name '_imaging' from 'PIL'
有參照固障排除的方法，仍然無法開啟瀏覽器
最後透過原始碼執行MaxBot 終於可以開啟

BUT!
又出現驗證碼無法自動KEY IN問題

錯誤截圖如下：

拓元
---
<img width="1104" alt="截圖 2024-02-01 上午3 02 11" src="https://github.com/max32002/tixcraft_bot/assets/158338013/77342b40-1fee-472d-a90c-e7af3405c8e7">

遠大
---
<img width="1250" alt="截圖 2024-02-01 上午3 08 52" src="https://github.com/max32002/tixcraft_bot/assets/158338013/ea210075-d099-48bf-815a-5c33aae719ee">

ibon
---
<img width="565" alt="截圖 2024-02-01 上午3 11 54" src="https://github.com/max32002/tixcraft_bot/assets/158338013/ba0e4487-9f54-4b82-acd0-d09d59f877f2">

目前Python版本為3.9.13

有測試過大大最新開發的MaxBot Plus擴件，
目前拓元、ibon可以自動帶入驗證碼
但是遠大無法

謝謝大大

**Comment by max32002** [comment]
ddddocr 元件沒被安裝

annannn123 ***@***.***> 於 2024年2月1日 週四 上午3:30 寫道：

**Comment by max32002** [comment]
請參考這部影片的解法, 
透過原始碼執行MaxBot教學影片： https://youtu.be/HpVG91j0lbI

**Step 1: 取得source code:**

`git clone https://github.com/max32002/tixcraft_bot.git`

**Step 2: 進入 clone 的資料夾: tixcraft_bot:**

`cd tixcraft_bot `

**Step 3: 安裝第三方套件:**

`python3 -m pip install -r pip-req.txt`

**Step 4: 執行設定界面主桯式:**

`python3 settings.py`

如果遇到MaxBot 改版, 請重新操作上面4個步驟一次, 即可取得新的版本.

如果MaxBot 沒改版, 第二次要再執行的話, 使用 Step 2 + Step 4, 這2行指令, 就可以執行 MaxBot.

### 在 macOS 裡，如何切換 python 版本?

網路上有很多做法，比較簡單的是在 Terminal app 裡，執行:

```
sudo rm -rf /Library/Frameworks/Python.framework/
rm -rf /usr/local/bin/python*
```

然後再到下面的網址裡挑選想要的 stable（穩定版的）python 版本即可:
https://www.python.org/downloads/macos/

**Comment by annannn123** [comment]
謝謝大大回覆
