### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL' 這個狀況怎麼處理

### ISSUE THREAD

**Issue by hidindin** [max32002/tixcraft_bot#174]
ImportError: cannot import name '_imaging' from 'PIL'

您好，使用的電腦是mac，試了好幾次無法跳出搶票視窗
想詢問能夠怎麼處理，謝謝！

**Comment by max32002** [comment]
請參考這部影片的解法, 
透過原始碼執行MaxBot教學影片： https://youtu.be/HpVG91j0lbI

Step 1: 取得source code:

`git clone https://github.com/max32002/tixcraft_bot.git`

Step 2: 進入 clone 的資料夾: tixcraft_bot:

`cd tixcraft_bot `

Step 3: 安裝第三方套件:

`python3 -m pip install -r pip-req.txt`

Step 4: 執行設定界面主桯式:

`python3 settings.py`

如果遇到MaxBot 改版, 請重新操作上面4個步驟一次, 即可取得新的版本.

如果MaxBot 沒改版, 第二次要再執行的話, 使用 Step 2 + Step 4, 這2行指令, 就可以執行 MaxBot.

如果你是 ARM CPU 應該會在 Step 3 就顯示錯誤訊息, 解法: https://github.com/max32002/tixcraft_bot/issues/82#issuecomment-1878986084

### 在 macOS 裡，如何切換 python 版本?

網路上有很多做法，比較簡單的是在 Terminal app 裡，執行:

```
sudo rm -rf /Library/Frameworks/Python.framework/
rm -rf /usr/local/bin/python*
```

然後再到下面的網址裡挑選想要的 stable（穩定版的）python 版本即可:
https://www.python.org/downloads/macos/

使用 venv 是更好的解法, 可以同時存在多個 python 版本, 缺點就是對不懂電腦的人, 難度會較高一點點.

venv 在網路上有超級多的教學文章, 有空的話可以參考看看這篇:
https://stackoverflow.max-everyday.com/2023/02/python-venv-django/

如果還有遇到其他的問題, 歡迎再開新的issue.
