### ISSUE TITLE
web driver not accessible!

### ISSUE THREAD

**Issue by jeffsnack** [max32002/tixcraft_bot#177]
Settings.py可以正常運作,但在運行chrome_tixcraft.py的時候會遇到以下錯誤

maxbot app version: MaxBot (2024.01.20)
python version: 3.12.1
platform: macOS-14.2-arm64-arm-64bit
homepage: https://www.indievox.com/
browser: safari
webdriver_type: selenium
create web driver object fail @_@;
web driver not accessible!

**Comment by max32002** [comment]
透過原始碼的執行方法
https://github.com/max32002/tixcraft_bot?tab=readme-ov-file#how-to-execute-source-code

透過原始碼執行MaxBot教學影片： https://youtu.be/HpVG91j0lbI
Step 1: 取得source code:
git clone https://github.com/max32002/tixcraft_bot.git
Step 2: 進入 clone 的資料夾: tixcraft_bot:
cd tixcraft_bot
Step 3: 安裝第三方套件:
python3 -m pip install -r pip-req.txt
Step 4: 執行設定界面主桯式:
python3 settings.py
如果遇到MaxBot 改版, 請重新操作上面4個步驟一次, 即可取得新的版本.
如果MaxBot 沒改版, 第二次要再執行的話, 使用 Step 2 + Step 4, 這2行指令, 就可以執行 MaxBot.

如果你是 ARM CPU 應該會在 Step 3 就顯示錯誤訊息, 解法:
https://github.com/max32002/tixcraft_bot/issues/82#issuecomment-1878986084
