### ISSUE TITLE
web driver not accessible!

### ISSUE THREAD

**Issue by yunimm** [max32002/tixcraft_bot#178]
環境：mac m1 晶片 / python3.10
程式版本：maxbot app version: MaxBot (2024.01.20)
情境：搶票前一天測試都正常，隔天再次運行程式時會報錯
```
WebDriver object is still None..., try download by uc.
HTTP Error 404: Not Found
create web drive object by undetected_chromedriver fail!
Unable to use undetected_chromedriver,
try to use local chromedriver to launch chrome browser.
create web driver object fail @_@;
web driver not accessible!
```

**Comment by max32002** [comment]
訊息上來看, 是無法取得 webdriver, 解法:
https://max-everyday.com/2023/11/maxbot-troubleshooting/#download_chromedriver_fail

**Comment by leoho0722** [comment]
有嘗試過解法一跟解法二，但還是遇到一樣問題，再麻煩您解答了，感謝

電腦環境

* Apple M1
* macOS Sonoma 14.3.1
* Python 3.10.13 (使用 Homebrew 安裝)

MaxBot 版本：2024.01.20 (透過原始碼執行)

<img width="770" alt="截圖 2024-02-18 23 44 28" src="https://github.com/max32002/tixcraft_bot/assets/73574800/8552cca7-02a0-4270-870d-8dd1723587df">

**Comment by max32002** [comment]
如果您是要在拓元上使用，建議您模擬為Intel CPU.

先手動刪除webdriver 目錄下的chrome drive 後，再執行一次看看。

Leo Ho ***@***.***> 於 2024年2月18日 週日 下午11:49 寫道：
