### ISSUE TITLE
web driver not accessible!

### ISSUE THREAD

**Issue by tongni0000** [max32002/tixcraft_bot#179]
啟動時，網頁持續閃退，不知道有沒有什麼解決辦法
電腦環境

Apple M2 pro
macOS Sonoma 14.3.1
Python 3.9.13 
<img width="1049" alt="截圖 2024-02-21 凌晨1 17 27" src="https://github.com/max32002/tixcraft_bot/assets/160644629/a2eb8b5e-9f78-43a0-af20-eb414b53030c">

**Comment by max32002** [comment]
請模擬 arm cpu 為 intel CPU 看看,

或手動下載您的截圖裡的 zip 檔後, 手動地執行 chromedriver 看看.
----
透過原始碼的執行方法
https://github.com/max32002/tixcraft_bot?tab=readme-ov-file#how-to-execute-source-code

透過原始碼執行MaxBot教學影片： https://youtu.be/HpVG91j0lbI
Step 1: 取得source code:
git clone https://github.com/max32002/tixcraft_bot.git
Step 2: 進入 clone 的資料夾: tixcraft_bot:
cd tixcraft_bot
Step 3: 安裝第三方套件:
python3 -m pip install -r pip-req.txt
Step 4: 執行設定界面主桯式:
python3 settings.py
如果遇到MaxBot 改版, 請重新操作上面4個步驟一次, 即可取得新的版本.
如果MaxBot 沒改版, 第二次要再執行的話, 使用 Step 2 + Step 4, 這2行指令, 就可以執行 MaxBot.

如果你是 ARM CPU 應該會在 Step 3 就顯示錯誤訊息, 解法:
https://github.com/max32002/tixcraft_bot/issues/82#issuecomment-1878986084
