### ISSUE TITLE
您好，請問這個問題是甚麼呢?

### ISSUE THREAD

**Issue by 110368145** [max32002/tixcraft_bot#18]
![螢幕擷取畫面 2023-01-11 225201](https://user-images.githubusercontent.com/94379138/211837580-9cb11792-c23a-4af3-929c-79b4d94f3579.png)

**Comment by jacky790125** [comment]
同狀況，更新 chorme 到 109 版本後已解決。

**Comment by 110368145** [comment]
好的謝謝。

**Comment by max32002** [comment]
https://max-everyday.com/2018/03/tixcraft-bot/#chrome_version
如果你出現下列的錯誤訊息：

This version of ChromeDriver only supports Chrome version xxx, Current broswer version is yyy.
翻譯成中文：ChromeDriver 元件版本只支援 xxx 版，你目前瀏覽器是 yyy 版。

元件與chrome瀏覧器版本不一致造成無法執行，請更新 chrome 為最近版本。

每1到2個月可能會有1天會遇到chrom瀏覽器全球的改版，即使在chrome瀏覽器裡按檢查更新，或是重新在chrome網站下載，也升級不到最新的版本。因為全球的用戶太多了，所以沒辦法每一個地區都即時或短時間內使用到最新的chrome版本。

解決辦法：

請手動到 chromedriver 網站下載與你的瀏覽器相同版本的 chromedriver 檔案，下載並解壓縮後，再複製到搶票程式的 /webdriver/ 目錄下。如果不知道怎麼操作的話，也沒關係，過二天你的chrome瀏覽器就可以升級到最新的版本。
