### ISSUE TITLE
macOS 的 Chrome開啟n次後即關閉

### ISSUE THREAD

**Issue by AS-Morning** [max32002/tixcraft_bot#180]
執行機器人後，會開啟Chrome幾次(通常是2次）後就閃退，並且不會到指定的購票網站，出現的script如下 ： 
maxbot app version: MaxBot (2024.01.19)
python version: 3.10.10
platform: macOS-13.4-arm64-arm-64bit
homepage: https://kktix.com
browser: chrome
webdriver_type: undetected_chromedriver
ChromeDriver exist: webdriver/chromedriver
Message: Service webdriver/chromedriver unexpectedly exited. Status code was: -9

Deleting exist and download ChromeDriver again.
CHROME >= 115, using mac-arm64 as architecture identifier
download webdriver from url: https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.69/mac-arm64/chromedriver-mac-arm64.zip
Message: Service webdriver/chromedriver unexpectedly exited. Status code was: -9

WebDriver object is still None..., try download by uc.
HTTP Error 404: Not Found
create web drive object by undetected_chromedriver fail!
Unable to use undetected_chromedriver, 
try to use local chromedriver to launch chrome browser.
create web driver object fail @_@;
web driver not accessible!

------------------------------------------------------------------------------------------------------------------------------
已確認Webdriver正常執行，且已試過將執行檔放入tixcraft_bot/webdriver，皆無效。

**Comment by HPJ1996** [comment]
這個和我遇到的問題一樣 (https://github.com/max32002/tixcraft_bot/issues/161)
我的解決方法是先把python套件全部升級 同時798~833註解掉
讓他直接跑 838,839 的讀取webdriver就可以了

**Comment by AS-Morning** [comment]
想請問798~833是指chrome_tixcraft.py的行數嗎？ 
我目前試了一下改成以下 ： 
# try:
               # chromedriver_autoinstaller_max.install(path=webdriver_path, make_version_dir=False)
               # options = get_uc_options(uc, config_dict, webdriver_path)
               # driver = uc.Chrome(driver_executable_path=chromedriver_path, options=options)
           # except Exception as exc2:
               # print(exc2)
               # pass
   # else:
       # print("WebDriver not found at path:", chromedriver_path)

   # if driver is None:
       # print('WebDriver object is still None..., try download by uc.')
       # try:
           # options = get_uc_options(uc, config_dict, webdriver_path)
           # driver = uc.Chrome(options=options)
       # except Exception as exc:
           # print(exc)
           # error_message = str(exc)
           # left_part = None
           # if "Stacktrace:" in error_message:
               # left_part = error_message.split("Stacktrace:")[0]
               # print(left_part)

           # if "This version of ChromeDriver only supports Chrome version" in error_message:
               # print(CONST_CHROME_VERSION_NOT_MATCH_EN)
               # print(CONST_CHROME_VERSION_NOT_MATCH_TW)
           # pass

   # if driver is None:
       # print("create web drive object by undetected_chromedriver fail!")

       # if os.path.exists(chromedriver_path):
            # print("Unable to use undetected_chromedriver, ")
            # print("try to use local chromedriver to launch chrome browser.")
            # driver_type = "selenium"
           # driver = load_chromdriver_normal(config_dict, driver_type)
       # else:
           # print("建議您自行下載 ChromeDriver 到 webdriver 的資料夾下")
           # print("you need manually download ChromeDriver to webdriver folder.")

    return driver
但就連chrome都不開了，還是我有理解錯誤？謝謝您。

Python的版本是3.10，之前好像看到.10目前比較穩定，不確定您是用.11還是.10，想說再新一點是不是不太好。

感謝您的分享～～～

**Comment by HPJ1996** [comment]
你註解錯行數啦
我是用 Python 3.10.8 然後手動下載webdriver
```
def load_chromdriver_uc(config_dict):
    import undetected_chromedriver as uc

    show_debug_message = True       # debug.
    show_debug_message = False      # online

    if config_dict["advanced"]["verbose"]:
        show_debug_message = True

    Root_Dir = get_app_root()
    webdriver_path = os.path.join(Root_Dir, "webdriver")
    chromedriver_path = get_chromedriver_path(webdriver_path)

    if not os.path.exists(webdriver_path):
        os.mkdir(webdriver_path)

    if not os.path.exists(chromedriver_path):
        print("ChromeDriver not exist, try to download to:", webdriver_path)
        try:
            chromedriver_autoinstaller_max.install(path=webdriver_path, make_version_dir=False)
            if not os.path.exists(chromedriver_path):
                print("check installed chrome version fail, download last known good version.")
                chromedriver_autoinstaller_max.install(path=webdriver_path, make_version_dir=False, detect_installed_version=False)
        except Exception as exc:
            print(exc)
    else:
        print("ChromeDriver exist:", chromedriver_path)


    driver = None
    '''
    以下註解
    if os.path.exists(chromedriver_path):
        # use chromedriver_autodownload instead of uc auto download.
        is_cache_exist = clean_uc_exe_cache()

        try:
            options = get_uc_options(uc, config_dict, webdriver_path)
            driver = uc.Chrome(driver_executable_path=chromedriver_path, options=options, headless=config_dict["advanced"]["headless"])
        except Exception as exc:
            print(exc)
            error_message = str(exc)
            left_part = None
            if "Stacktrace:" in error_message:
                left_part = error_message.split("Stacktrace:")[0]
                print(left_part)

            if "This version of ChromeDriver only supports Chrome version" in error_message:
                print(CONST_CHROME_VERSION_NOT_MATCH_EN)
                print(CONST_CHROME_VERSION_NOT_MATCH_TW)

            # remove exist chromedriver, download again.
            try:
                print("Deleting exist and download ChromeDriver again.")
                os.unlink(chromedriver_path)
            except Exception as exc2:
                print(exc2)
                pass

            try:
                chromedriver_autoinstaller_max.install(path=webdriver_path, make_version_dir=False)
                options = get_uc_options(uc, config_dict, webdriver_path)
                driver = uc.Chrome(driver_executable_path=chromedriver_path, options=options)
            except Exception as exc2:
                print(exc2)
                pass
    else:
        print("WebDriver not found at path:", chromedriver_path)
    以上註解
    '''

    if driver is None:
        print('WebDriver object is still None..., try download by uc.')
        try:
            options = get_uc_options(uc, config_dict, webdriver_path)
            driver = uc.Chrome(options=options)
        except Exception as exc:
            print(exc)
            error_message = str(exc)
            left_part = None
            if "Stacktrace:" in error_message:
                left_part = error_message.split("Stacktrace:")[0]
                print(left_part)

            if "This version of ChromeDriver only supports Chrome version" in error_message:
                print(CONST_CHROME_VERSION_NOT_MATCH_EN)
                print(CONST_CHROME_VERSION_NOT_MATCH_TW)
            pass

    if driver is None:
        print("create web drive object by undetected_chromedriver fail!")

        if os.path.exists(chromedriver_path):
            print("Unable to use undetected_chromedriver, ")
            print("try to use local chromedriver to launch chrome browser.")
            driver_type = "selenium"
            driver = load_chromdriver_normal(config_dict, driver_type)
        else:
            print("建議您自行下載 ChromeDriver 到 webdriver 的資料夾下")
            print("you need manually download ChromeDriver to webdriver folder.")

    return driver
```

**Comment by max32002** [comment]
有空的話, 請幫忙測試看看 2024-02-03 這個版本. 
https://github.com/max32002/tixcraft_bot/commit/357cf7050d7b1f44519892764f7617f207a138d8

**Comment by HPJ1996** [comment]
@max32002 感謝修正
不過此版本會開啟兩個瀏覽器視窗 
第一個會停留在開啟頁面無反應 第二個可正常搶票

```
➜  tixcraft_bot git:(master) ✗ python3 settings.py
2024-03-06 17:55:53.572 Python[30495:9956131] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
server running on port: 16888
setting app version: MaxBot (2024.02.03)
python version: 3.10.8
platform: macOS-14.2.1-arm64-arm-64bit
run button pressed.
save config result: True
execute in shell mode.
try python3
maxbot app version: MaxBot (2024.02.03)
python version: 3.10.8
platform: macOS-14.2.1-arm64-arm-64bit
homepage: https://tixcraft.com
browser: brave
webdriver_type: undetected_chromedriver
ChromeDriver exist: webdriver/chromedriver
Message: Service webdriver/chromedriver unexpectedly exited. Status code was: -9

goto url: https://tixcraft.com
https://tixcraft.com/
```

**Comment by max32002** [comment]
找到原因，也已修正，的樣子。
https://github.com/max32002/tixcraft_bot/commit/fe22914be9e3a52573f7619314fe353b4f3550fb

**Comment by hwanghwangwilly** [comment]
TypeError: '>' not supported between instances of 'str' and 'int'
跳出這個且網頁自動關閉

**Comment by hidindin** [comment]
@HPJ1996 
您好，我也碰到了和版主一樣的問題，想請問手動下載webdriver指的是哪裡的檔案呢？
以及您說的註解的部分，是進到chrome_tixcraft.py後把它刪除嗎？還是更改成您書寫的內容？
不好意思，對這些很不熟悉，再麻煩您說明！謝謝！

**Comment by max32002** [comment]
這個問題，應該是只有在macOS arm CPU 才會遇到，新的版本應該是已經沒有這個問題，的樣子。

hidindin ***@***.***> 於 2024年7月24日 週三 下午9:27 寫道：
