### ISSUE TITLE
ticketPlus 重整判定問題

### ISSUE THREAD

**Issue by tsukiyoK** [max32002/tixcraft_bot#182]
HI Max大，
在ticketPlus的頁面中邏輯應該可以簡單歸納為
爬空位(比對設定關鍵字)>>點滿我要的張數>>key驗證碼送出，
送出後ticketPlus好像會先打一個api刷新剩餘位置如果你選的沒有了就會原頁面跳alert()，
但此時bot好像會以為驗證碼沒過持續try驗證碼，
可能要確認一下重整頁面判斷?

另外請問一下如果再開賣時間前就開起來待機，
是不是開賣時間到要自己手動重整網頁? 

Thanks

**Comment by max32002** [comment]
請問, 這個問題, 有辦法在目前已開賣的場次裡複製出相同的問題嗎?

**Comment by max32002** [comment]
又過了2周, 先假設問題已解決. 如果還有遇到, 請再重開 issue, 謝謝.

**Comment by tsukiyoK** [comment]
抱歉前陣子一忙忘記回覆，
有點難在目前已開賣的場次重現，
要那種搶翻的場次才有機會碰到這個issue，
若下次有機會我想想怎麼重現，
感謝協助
