### ISSUE TITLE
解壓縮全部後未出現setting.exe

### ISSUE THREAD

**Issue by harmonnnnny** [max32002/tixcraft_bot#183]
![image](https://github.com/max32002/tixcraft_bot/assets/161233024/a7dc26d3-9e42-464a-9c69-452764fb3066)
windows11
Google Chrome 已更新最新版
python3.10

**Comment by max32002** [comment]
由於您下載的是原始碼, 所以不會有 .exe 檔.

參考網頁說明:
https://max-everyday.com/2018/03/tixcraft-bot/
