### ISSUE TITLE
Edge 瀏覽器搶票不會勾選同意與重整頁面

### ISSUE THREAD

**Issue by HPJ1996** [max32002/tixcraft_bot#184]
使用 edge 搶票似乎不會載入 `Maxbotplus_1.0.0` 與  `Maxblockplus_1.0.0`
又因為 `CONST_CHROME_FAMILY = ["chrome","edge","brave"]` 
因此 `is_agree_at_webdriver` 和 `is_reload_at_webdriver` 被設為 `false`
而不會重新整理與勾選同意

**Comment by max32002** [comment]
在 edge 測試, 功能都正常. 

is_agree_at_webdriver  被設為 false 可能是參數:
config_dict["advanced"]["chrome_extension"]
這個設定值: 允許在 chrome family browser 不載入 chrome exetsion.

![msedge_2024-02-27_16-41_bn](https://github.com/max32002/tixcraft_bot/assets/4498233/7cf10a5d-5de1-4a05-89d4-15f717db36a3)
