### ISSUE TITLE
Sid 值登入問題

### ISSUE THREAD

**Issue by Lisachen591002** [max32002/tixcraft_bot#185]
最近發現了20230722的版本還可以正常使用gmail登入，從9月份到目前的版本就需要依賴SID值登入。

今天測試20240201的版本，今天取完SID值後，第一次嘗試登入成功，但把機器人關掉後，再重新開啟機器人嘗試第二次就失敗了，重新登入的間隔時間不到五分鐘，也是使用同一個SID值。後來再從正常瀏覽器中，重新登入並重新取一個新的SID值貼到機器人上，還是一樣沒辦法登入！不知道這個該怎麼解🙏🏻

另外想詢問IBON的Sid 值要如何取得，因為頁面沒有如https://youtu.be/QnaCRQjAlng上中的cookie 資料

**Comment by Lisachen591002** [comment]
後來測試換一個帳號gmail再取一次sid值，依然無法登入🙏🏻

**Comment by max32002** [comment]
1: 請問新鮮的 SID.

2: 影片說明1 - 2023-02-25：透過cookie的ibonqware登入ibon
https://youtu.be/QnaCRQjAlng

在正常的瀏覽器裡登入 Google/Facebook 帳號後, 或透過 cookie 的 SID 值登入。
詳細的討論參考: https://github.com/max32002/tixcraft_bot/issues/3

Q：如何在已經登入拓元帳號的瀏覽器，取得Cookies 的 SID值？
A：在 Windows 請按 F12 或 Ctrl + Shift + I, 在 macOS 請按 Cmd+Option+I, 即可叫出開發者工具(DevTools)，在畫面的 Appliction 分頁裡的 Storage 項目中的 Cookies 裡即取得拓元登入後的 SID值。
