### ISSUE TITLE
Ibon售票系統如何取Sid值

### ISSUE THREAD

**Issue by Lisachen591002** [max32002/tixcraft_bot#187]
想請問ibon售票系統取sid 值部分，有根據影片（https://youtu.be/QnaCRQjAlng）步驟，
但我的瀏覽器沒有影片上的鎖頭，點開cookie資料也沒有sid 值，似乎這個方法只適用於safari瀏覽器嗎？想請問chrome瀏覽器要怎麼取ibon Sid值謝謝🙏🏻

**Comment by max32002** [comment]
Q：如何在已經登入拓元帳號的瀏覽器，取得Cookies 的 SID值？
A：在 Windows 請按 F12 或 Ctrl + Shift + I, 在 macOS 請按 Cmd+Option+I,
即可叫出開發者工具(DevTools)，在畫面的 Appliction 分頁裡的 Storage 項目中的 Cookies 裡即取得拓元登入後的
SID值。

影片說明1 - 2023-02-25：透過cookie的ibonqware登入ibon
https://youtu.be/QnaCRQjAlng


Lisachen591002 ***@***.***> 於 2024年3月2日 週六 下午2:46 寫道：

**Comment by Lisachen591002** [comment]
F12 或 Ctrl + Shift + I, 在 macOS 請按 Cmd+Option+I，似乎只能取拓元系統的，但無法取ibon的ibonware 

但根據影片(https://youtu.be/QnaCRQjAlng)步驟，使用chrome瀏覽器登入ibon，沒有如影片上方的鎖頭畫面

**Comment by Lisachen591002** [comment]
![IMG_8813](https://github.com/max32002/tixcraft_bot/assets/132981011/71223406-516d-4fe0-975d-d1721286576a)

沒有影片中的鎖頭，請問ibon還能利用什麼方式取謝謝

**Comment by max32002** [comment]
似乎也可以。ibonqware.

Lisachen591002 ***@***.***> 於 2024年3月2日 週六 下午9:17 寫道：

**Comment by Lisachen591002** [comment]
如拓元開啟F12方法後，請問哪一部才是ibon的ibonqware謝謝🙏🏻
![IMG_8815](https://github.com/max32002/tixcraft_bot/assets/132981011/ad74d17c-2eef-4c43-8130-ad0c2107357a)

**Comment by max32002** [comment]
整串.
