### ISSUE TITLE
Mac M2 Sonoma 14.0 GUI畫面黑屏

### ISSUE THREAD

**Issue by Leooooooo121** [max32002/tixcraft_bot#189]
## 啟動畫面
<img width="580" alt="image" src="https://github.com/max32002/tixcraft_bot/assets/30442197/e1bd60b7-7387-4215-9602-302b3f71a15e">

## 啟動指令
<img width="878" alt="image" src="https://github.com/max32002/tixcraft_bot/assets/30442197/6735c893-8e8e-404f-9d5d-d267221205bf">

**Comment by max32002** [comment]
詳解: https://max-everyday.com/2023/11/maxbot-troubleshooting/#mac_black
安裝 python 3.10 or 3.9

**Comment by tiffanytut0225** [comment]
您好，請問是要裝 3.10 的哪一個版本？謝謝

![CleanShot 2024-03-07 at 09 09 54](https://github.com/max32002/tixcraft_bot/assets/42331417/312c53b2-0f09-461c-b04c-d483f8033d35)

**Comment by max32002** [comment]
都可以

tiffanytut0225 ***@***.***> 於 2024年3月7日 週四 上午9:11 寫道：
