### ISSUE TITLE
進去瀏覽器會error

### ISSUE THREAD

**Issue by aimer77777** [max32002/tixcraft_bot#19]
[11164] Failed to execute script 'chrome_tixcraft' due to unhandled exception!
想請問是瀏覽器的問題嗎
因為用舊版的也是同樣問題
但之前用都可以正常進入

**Comment by max32002** [comment]
升級為 chrome 109 版即可, 或:
https://www.facebook.com/maxbot.ticket/posts/667518968498866


aimer77777 ***@***.***> 於 2023年1月12日 週四 下午12:45 寫道：

**Comment by patds** [comment]
可以應改成 uc.Chrome(version_main=108)

**Comment by patds** [comment]
可以再  uc.Chrome 增加 version_main=108 參數

**Comment by max32002** [comment]
猜測, 現在(2023-03-05) 應該是都沒問題了, 如果還會發生, 請再開新的問題(issue).
