### ISSUE TITLE
maxbot無法chrome瀏覽器，安裝了webdriver也沒有辦法打開 

### ISSUE THREAD

**Issue by kenkennyleung** [max32002/tixcraft_bot#193]
主要的報錯代碼：
ImportError: cannot import name '_imaging' from 'PIL' (/Users/l*******/Downloads/ticket/maxbot/MaxBot.app/Contents/Resources/PIL/__init__.py)

可以請教下是什麼問題嗎

**Comment by max32002** [comment]
請改用原始碼執行.
https://github.com/max32002/tixcraft_bot?tab=readme-ov-file#how-to-execute-source-code

透過原始碼執行MaxBot教學影片： https://youtu.be/HpVG91j0lbI

Step 1: 取得source code:

git clone https://github.com/max32002/tixcraft_bot.git

Step 2: 進入 clone 的資料夾: tixcraft_bot:

cd tixcraft_bot 

Step 3: 安裝第三方套件:

python3 -m pip install -r pip-req.txt

Step 4: 執行設定介面主桯式:

python3 settings.py

如果不使用設定介面，直接執行主程式:

python3 chrome_tixcraft.py

如果不使用設定介面，直接執行主程式並套用特定的設定檔:

python3 chrome_tixcraft.py --input settings.json

如果遇到MaxBot 改版, 請重新操作上面4個步驟一次, 即可取得新的版本.

如果MaxBot 沒改版, 第二次要再執行的話, 使用 Step 2 + Step 4, 這2行指令, 就可以執行 MaxBot.

如果你是 ARM CPU 應該會在 Step 3 就顯示錯誤訊息, 解法: https://github.com/max32002/tixcraft_bot/issues/82#issuecomment-1878986084

不管是 macOS 還是 Windows 預設都是沒有 git 這個指令，如果 Step 1 執行後, 沒有檔案被下載, 請先安裝 git 到你的作業系統。或是使用github 網頁裡的 Download 功能把python 腳本下載。

如果你選擇下載 github 上的 zip 檔, 在 Step 2 進入目錄的指令可能會遇到問題, 因為「直接解壓縮」後的目錄名稱並不是 tixcraft_bot 而是 tixcraft_bot-master, 你在進入的資料夾名稱, 需要調整為你實際解壓縮後的目錄名稱。

透過瀏覽器下載 github 上的 zip 檔, 在 Windows / macOS / Linux 平台, 預設的路徑在「下載」(~/Download) 的資料夾, 你在執行的 Terminal 視窗的路徑, 與你解壓縮的路徑可能不同, 直接執行上面的指令, 會無法進入到預期的資料夾內。

Q: 取得source code後跑出來fatal: destination path 'tixcraft_bot' already exists and is not an empty directory.想問是什麼意思?

A: 執行 git clone 2次, 重覆取得 source code, 才會有這個問題, 如果 tixcraft_bot 目錄已經存在, 直接 cd tixcraft_bot 就可以了。 如果你想把已下載的刪除, 可以直把把 tixcraft_bot 目錄刪掉即可。 如果你想更新 source code, 可以重新下載, 或是先 cd tixcraft_bot 目錄後, 再執行 git pull , 可以更新 source code 為新的版本。
