### ISSUE TITLE
Mac M2版本 畫面異常

### ISSUE THREAD

**Issue by luowenyan04** [max32002/tixcraft_bot#194]
啟動後異常訊息如下
視窗僅出現checkbox

![image](https://github.com/max32002/tixcraft_bot/assets/25997637/ab96a2d6-eb03-4e28-a763-fa08419e70ee)

<img width="580" alt="image" src="https://github.com/max32002/tixcraft_bot/assets/25997637/67b7fce7-e39f-4cae-a5f4-b40dc24c2def">

**Comment by max32002** [comment]
請手動地刪除 python 3 之後, 再重新安裝一次即可, 詳細說明:
https://max-everyday.com/2023/11/maxbot-troubleshooting/#mac_black
