### ISSUE TITLE
KKTIX信用卡搶先購問題

### ISSUE THREAD

**Issue by a22625858** [max32002/tixcraft_bot#195]
![432791437_376325865232907_1449004045130252680_n](https://github.com/max32002/tixcraft_bot/assets/141715669/3a540597-317f-4d1c-93e3-2cd31321404a)
如果有信用卡搶先購他會停在這個畫面
不會自己去按下一步
想問是甚麼問題

**Comment by max32002** [comment]
因為還沒有提供這個功能，需要手動輸入。

a22625858 ***@***.***> 於 2024年3月22日 週五 上午11:13 寫道：

**Comment by max32002** [comment]
MaxBot 2024-03-08 KKIX 加購粉絲福利
之前可以用，在某一個版本之後，不小心忘改壞掉。
