### ISSUE TITLE
請問一下 畫面無法顯示問題

### ISSUE THREAD

**Issue by NeoOpenSource** [max32002/tixcraft_bot#197]
請問一下 是不是 出現這個問題 所以 GUI無法顯示出來？

 WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
exit settings

**Comment by max32002** [comment]
請參考下面網址做法，刪掉python 後，重新安裝為 python 3.10.X 版。
https://max-everyday.com/2023/11/maxbot-troubleshooting/#mac_black

**Comment by NeoOpenSource** [comment]
謝謝 我有查到原因 後來我還是放棄了 我改setting.json 然後去下commond run 比較快 感謝你的回覆
