### ISSUE TITLE
搶票程式無法使用

### ISSUE THREAD

**Issue by Jizz5566** [max32002/tixcraft_bot#2]
在Windows環境：自動開啟的Chrome視窗因為安全性問題無法使用Google帳號登入拓元，所以根本無法執行下一步，OAuth可能要檢查一下

在Linux環境：特別使用原始乾淨的Ubuntu 20.04，結果python套件缺東缺西根本無法執行，自己還要手動去安裝python。安裝python後執行setting.py，又出現no name selenium，又要pip install ，可是在此版Ubuntu無法自動安裝pip，又要user自己想辦法安裝pip，還不能安裝到pip3，否則一樣會出現不明錯誤訊息。
好不容易降版使用get-pip.py安裝pip2之後，再次執行settings.py，又出現其他錯誤訊息，這次換chromewebdriver，沒有在PATH找到
請問這程式release之前究竟有沒有測試過？

**Comment by Jizz5566** [comment]
補充 是使用 2d01130 這版commit

**Comment by CrazyRyan0812** [comment]
我在Ubuntu 20.04環境，乾淨安裝過後，安裝完google chrome後，linux版本執行是非常正常的哦
我跟你用的是同一個版本的commit
我相信max大是有做過測試才會release哦
你要從原始碼去編譯你本來就應該要有能力去pip install那些缺失的套件阿，每台電腦的環境根本就不同啊@@，而且我的pip功能也是正常的，你自己在安裝過程是不是有出甚麼問題？

**Comment by max32002** [comment]
已增加如何執行的說明，參考看看。

How to execute source code (透過原始碼的執行方法)
1: download chromedrive to "webdriver" folder: http://chromedriver.chromium.org/downloads

change the chromedrive in chrome_tixcraft.py, source code: chromedriver_path =Root_Dir+ "webdriver/chromedriver" the default path is the script path + "webdriver/chromedriver", my suggestion is make a new directory then move the chromedrive under new folder.

2: pip install selenium or pip3 install selenium

3: python settings.py or python3 settings.py

PS: this script able to run in python2 or python3. 
PS: 原始碼可以在python2 或 python3 下執行，請先確定你的python 執行環境下已安裝 selenium 或相關的套件，參考 pip-reg.txt。還需要手動下載新版的 chromedrive 或 firefox drive(geckodriver), 建議在 source code 下建立一個 webdrive 的目錄，並把 chromedirve 的執行檔放進去，或是手動地修改 chrome_tixcraft.py 裡的 chromedriver_path 為你環境下能存取到 chromedrive 的路徑。最後透過 python 或 python3 執行 settings.py 就可以有 GUI 的設定界面。

**Comment by max32002** [comment]
猜測, 現在(2023-03-05) 應該是都沒問題了, 如果還會發生, 請再開新的問題(issue).

Goolge 登入的問題合併到 #3  討論. 

Linux 的支援, 大多應該是OK, 但相容性與Windows/macOS 相較之下較差, 還有GUI 元件的 tkinter , 部份版本的Linux家族相容性較差, 驗證碼功能也可能會出問題, 還有問題的話, 請再開新的問題(issue).
