### ISSUE TITLE
Ibon 沒搶到回首頁

### ISSUE THREAD

**Issue by Salmon13** [max32002/tixcraft_bot#205]
您好，已經翻過問答。想請問使用機器人在Ibon搶票時，若尚未開賣，會跳回Ibon首頁，請問這是預期中的行為嗎？

以 [TANK演唱會](https://ticket.ibon.com.tw/ActivityInfo/Details/38328) 為例，我setting中設定日期關鍵字為"08"，在進入購票頁面後因為還沒開賣所以失敗，但會直接跳回Ibon首頁，而不是繼續待在此演唱會頁面嘗試。

**Comment by max32002** [comment]
修正於 2024-03-27 版:
06fb4e25cee5bd1bfec0042fd8cdcead6864adcd
