### ISSUE TITLE
cityline加了 cloudflare 進不了

### ISSUE THREAD

**Issue by PHC045** [max32002/tixcraft_bot#206]
您好,上個月試的時候還可以進的,今天試的時候因為查到機械人就進不了了,應該是官方加強了偵測.
只是來通知一聲,如果能修改到當然最好,不行也没關係.
最後感謝Max大大在kktix幫我搶到票!!

**Comment by max32002** [comment]
是的, 目前 cityline 除了使用 reCAPTCHA 還加了 cloudflare.

**Comment by max32002** [comment]
已解決, 
MaxBot 2024-04-02
(2024-04-12) cityline 撞牆心得
https://youtu.be/cLFWyI1BLyw

MaxBot 2024-04-01
Cityline 自動輸入張數,票價,日期
https://youtu.be/o32TJ6jcS1M
