### ISSUE TITLE
cityline不能用的话怎么开虚拟机撞墙呢呢 

### ISSUE THREAD

**Issue by lizi672** [max32002/tixcraft_bot#209]

**Comment by max32002** [comment]
* cityline 已可以使用, 
* 如果是在虛擬主機上排機, 可以增加排到的機會。

MaxBot 2024-04-02
(2024-04-12) cityline 撞牆心得
https://youtu.be/cLFWyI1BLyw

MaxBot 2024-04-01
Cityline 自動輸入張數,票價,日期
https://youtu.be/o32TJ6jcS1M
