### ISSUE TITLE
驗證碼輸入後不會自動送出

### ISSUE THREAD

**Issue by ybph** [max32002/tixcraft_bot#21]
20230112-ver3
猜測後自動送出打勾了還是不會自動送出

**Comment by max32002** [comment]
請幫上附上黑色框框裡的訊息，才會知道是什麼原因造成。 感謝。

**Comment by max32002** [comment]
也許，新版本，已修改掉這個錯誤，請重新下載新版本測試看看。

**Comment by max32002** [comment]
先關閉這一個issue, 如果還有問題, 請再開新的issue, 並附上黑色視窗裡的訊息. arm CPU 的 電腦暫時還沒有支援驗證碼功能, 詳細的說明, 請google ddddocr.
