### ISSUE TITLE
您好 請問您是怎麼驗證通關cityline真人驗證的？

### ISSUE THREAD

**Issue by Yul998** [max32002/tixcraft_bot#210]

**Comment by max32002** [comment]
drission page, nodriver 都行。

Yul998 ***@***.***> 於 2024年4月11日 週四 下午11:52 寫道：

**Comment by max32002** [comment]
把 python 把腳本從 selenium 改寫為 DrissionPage 或 nodriver 格式就會過 CloudFlare:
https://github.com/g1879/DrissionPage/
https://github.com/ultrafunkamsterdam/nodriver
