### ISSUE TITLE
請問一下Cityline是如何通過過真人驗證

### ISSUE THREAD

**Issue by SamueLai1** [max32002/tixcraft_bot#212]
我是用windows搶票的
嘗試用過google, 但被說這個瀏覽器或應用程式可能有安全疑慮。
Windows是如何找到cookie然後找到SID? 是用跟托元同一個方法嗎還是有其他方法?
另外也試過使用facebook登入 但輸入資料後視窗就沒了 然後command說
NoSuchWindowException at this url:
quit bot by NoSuchWindowException
可以怎樣解決?
還有什麼其他的登入方法能通過機器人的證人驗證?

**Comment by max32002** [comment]
把 python 把腳本從 selenium 改寫為 DrissionPage 或 nodriver 格式就會過 CloudFlare:
https://github.com/g1879/DrissionPage/
https://github.com/ultrafunkamsterdam/nodriver

SID 從 cookie 取得, 參考:
https://github.com/max32002/tixcraft_bot/issues/3
