### ISSUE TITLE
Cityline 登入問題

### ISSUE THREAD

**Issue by SamueLai1** [max32002/tixcraft_bot#215]
請問一下Cityline搶票應該用哪一個登入？
因為昨天試了用Facebook登入 登入後搶票機器人開的chrome就直接關了
是出了什麼問題嗎？

**Comment by max32002** [comment]
用一次性密碼.

MaxBot 2024-04-02版, 
(2024-04-12) cityline 撞牆心得
https://youtu.be/cLFWyI1BLyw

MaxBot 2024-04-01版, 
Cityline 自動輸入張數,票價,日期
https://youtu.be/o32TJ6jcS1M

**Comment by imzoom77** [comment]
请问cityline如果用程序直接填登陆账号的话，为啥登陆后就无法进入买票页面了
