### ISSUE TITLE
关于ciytline无法登录

### ISSUE THREAD

**Issue by luyitian19995** [max32002/tixcraft_bot#216]
登录时人机识别无法通过，正常网页可通过，MAXBOT打开的窗口无法登录

**Comment by luyitian19995** [comment]
www.cloudflare.com 遭到封鎖www.cloudflare.com 拒絕連線。

**Comment by burnningwings** [comment]
请问有解决办法吗？我也遇到这个问题

**Comment by max32002** [comment]
請使用 2024-04-03 版, 程式會自動切換 webdriver 為: nodriver 模式.
