### ISSUE TITLE
cityline4月3版本执行源码

### ISSUE THREAD

**Issue by Chaeryrong** [max32002/tixcraft_bot#218]
4月3日版本pycharm执行settin
![屏幕截图 2024-04-14 161634](https://github.com/max32002/tixcraft_bot/assets/147048257/35595a25-576f-472a-a789-c8f1d6f8b727)
g出现server rejected WebSocket connection: HTTP 500，cityline然后一直重复刷新，没有登陆界面出来

**Comment by max32002** [comment]
測試功能無誤, 請直接用python 執行看看, 我跟 pycharm 不熟.

**Comment by Chaeryrong** [comment]
python版本是3.11，執行有影響嗎，試過cmd執行python源碼，setting似乎無反應

**Comment by max32002** [comment]
理論上, 可以使用 python 3.11.

python settings.py 無反應, 我沒遇到過, 無解.

可以試看看打包好的執行檔, 或是請學過python 的工具人協助你執行源碼。
