### ISSUE TITLE
kktix搶購tix-get-go活動不會自動按下一步

### ISSUE THREAD

**Issue by dbpanicvin** [max32002/tixcraft_bot#221]
https://kktix.com/events/waterbombhk2024-2day-njcs9sw5/registrations/new
在tix-get-go活動中只會自動選票價和點勾選框,幷不會按下一步
bot版本2024.03.18 & 2024.04.08
![PixPin_2024-04-19_14-24-35](https://github.com/max32002/tixcraft_bot/assets/22132033/d44c776c-144f-44d8-9d7a-7135038d7adc)

**Comment by max32002** [comment]
你試看看 webdriver 為 nodriver 看看。

**Comment by dbpanicvin** [comment]
> 你試看看 webdriver 為 nodriver 看看。

當前鏈接票已售完 待日後有類似演出時我再嘗試 謝謝Max的解決方案

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/commit/fe22914be9e3a52573f7619314fe353b4f3550fb

**Comment by joeryo222222** [comment]
> > 你試看看 webdriver 為 nodriver 看看。
> 
> 當前鏈接票已售完 待日後有類似演出時我再嘗試 謝謝Max的解決方案

https://kktix.com/events/firstjump2024/registrations/new
這個可以測試

**Comment by max32002** [comment]
使用 2024-04-09 版，沒有解決？

**Comment by joeryo222222** [comment]
解決了， 謝謝max 大大

「Max ***@***.***>」在 2024年4月20日 週六，23:32 寫道：
