### ISSUE TITLE
Cityline 在以event開頭網頁的排隊頁面不會自動刷新

### ISSUE THREAD

**Issue by dbpanicvin** [max32002/tixcraft_bot#235]
https://event.cityline.com/utsvInternet/NCTDREAMINHK2024/login?lang=TW
![屏幕截图 2024-04-30 102723](https://github.com/max32002/tixcraft_bot/assets/22132033/41454909-b3ca-4220-b35c-ba6d932c4315)

**Comment by max32002** [comment]
請在試試 2024-04-13 這一個版本號碼, 是否有辧法成功撞牆.
