### ISSUE TITLE
cityline選票被踢出去了

### ISSUE THREAD

**Issue by tungzip** [max32002/tixcraft_bot#237]
Max你好，
剛剛我使用2024-04-13 release版本5分鐘刷進去了
進去選票的時候，不知道是不是刷太快了，彈出一個系統繁忙就被踢出去，重新排隊了，
![微信图片_20240503120246](https://github.com/max32002/tixcraft_bot/assets/41478294/366aebad-20f5-4ba0-8e08-e5556912c865)
最後還是搶到了，讚👍
還有一個美中不足就是電腦系統内存占用好像有點高，開了5個網頁排隊，16GB的RAM就跑滿了，卡到網頁崩潰了，不知道能否優化一下，感謝
![微信图片_20240503122002](https://github.com/max32002/tixcraft_bot/assets/41478294/8fbf0f33-afbb-4597-a17b-518e50b0eedf)

**Comment by max32002** [comment]
請增加 Windows 的虛擬記憶體:
https://zh-tw.emeditor.com/increase-virtual-memory/

如果您有 16GB RAM, 建議設定為 16GB, 如果需要開啟「大量」視窗的話，可以再加大這個數字。
