### ISSUE TITLE
HKTicketing Bugs

### ISSUE THREAD

**Issue by NFTripunch** [max32002/tixcraft_bot#24]
When queuing on the hkticketing website, it will not reload automatically after 10 seconds delay (stuck in 0 seconds, the terminal gives no output). The link shown is https://premier.hkticketing.com/ while normally it should be https://queue.hkticketing.com/hotshow.html which will reload after 10 seconds.

**Comment by Frankyyeah** [comment]
I have the same issue too, seems like the website detected there is a bot and automatically ban from accessing the webpage.

**Comment by Sphinx-ace** [comment]
我也遇到了同样的问题，而且前几天并没有出现这个问题。是不是最近刷的人太多？

**Comment by max32002** [comment]
不是哦，是因為Google 的 reCaptcha 檢測到正在使用機器人，所以會顯示上面的網頁內容。目前暫時要先跟快達票說bye-bye, 等可以避開被 reCaptcha 檢測到之後，再回來支援。

**Comment by max32002** [comment]
由於目前官方已經可以檢測到機器人, 暫時無解, 相關討論合併到: https://github.com/max32002/tixcraft_bot/issues/36
