### ISSUE TITLE
拓元網站無法登入

### ISSUE THREAD

**Issue by chan15** [max32002/tixcraft_bot#241]
版本：chrome_tixcraft.20240415_Win10_Win11.zip

設定頁面開啟拓元網站後，點選 Google 登入，輸入 email 後顯示**無法登入帳戶**

![image](https://github.com/max32002/tixcraft_bot/assets/1229833/2e728d81-dfa2-49d8-8108-f0dcf7c7cb97)

**Comment by chaingthomas** [comment]
請參考 https://github.com/max32002/tixcraft_bot/issues/3
