### ISSUE TITLE
選了用edge 開還是會開啟chrome

### ISSUE THREAD

**Issue by tcwtso** [max32002/tixcraft_bot#244]
你好max,

請問我選了edge 開啟後, 按搶票後還是開啟chrome, 請問怎樣解決? 謝謝

![image](https://github.com/max32002/tixcraft_bot/assets/54352836/a4e20e41-6742-4687-90b8-6c15d6b34fb4)

**Comment by max32002** [comment]
Nodriver 目前只支援chrome.

tcwtso ***@***.***> 於 2024年5月10日 週五 上午10:34 寫道：

**Comment by max32002** [comment]
後來, 發現是程式的錯誤, 已在新版本修正. 試看看 2024-04-16 以後的版本號碼.
