### ISSUE TITLE
KKTIX的register_info查询不到inventory了

### ISSUE THREAD

**Issue by Zuozhuo** [max32002/tixcraft_bot#245]
![image](https://github.com/max32002/tixcraft_bot/assets/116483151/42f8d20e-592b-45da-9f18-630d24c4f52a)
之前inventory里面有COMING_SOON, SOLD_OUT, OUT_OF_STOCK等状态， 现在查询不到了，无论是否开放购票，这一项都为空值

**Comment by max32002** [comment]
感謝告知. 已刪除相關程式碼.
