### ISSUE TITLE
設定檔介面bug

### ISSUE THREAD

**Issue by mkcs121** [max32002/tixcraft_bot#252]
1. 選用chrome以外的瀏覽器，存檔後按搶票還是啟動了chrome
2. 結束程序後，原本的webdriver會無緣無故地從undetected chromedriver自動儲存為nodriver

**Comment by max32002** [comment]
你應該是使用了 cityline, 因為 cityline 只能使用 chrome + nodriver, 無法使用這個組合以外。

**Comment by mkcs121** [comment]
> 你應該是使用了 cityline, 因為 cityline 只能使用 chrome + nodriver, 無法使用這個組合以外。

是Cityline沒錯，原來是比較特別，之後有機會再試自動排隊有沒有效，據悉自動重試會被攔截
