### ISSUE TITLE
搶票設定問題

### ISSUE THREAD

**Issue by Sylt016** [max32002/tixcraft_bot#258]
請問想要選擇紅框內的場次，要怎麼設定後台呢？

因為6880有兩天，且每一天不同價位又分開頁面，有點複雜怕設定錯誤
![IMG_0956](https://github.com/max32002/tixcraft_bot/assets/172303692/4d6cc1ce-49b8-4694-a5d4-bc858d6a4f1e)

**Comment by max32002** [comment]
參考看看，網頁上的case study.說明。

Sylt016 ***@***.***> 於 2024年6月11日 週二 上午1:22 寫道：

**Comment by max32002** [comment]
如果還有需要協助的地方，請再 reopen issue 或 開新的 issue.
