### ISSUE TITLE
開賣時驗證碼不會自動輸入

### ISSUE THREAD

**Issue by c654321000** [max32002/tixcraft_bot#26]
您好，感謝您提供這個程式，在今天五月天開賣的時候，不知道是不是卡頓的原因 驗證碼不會自己輸入 在開賣之前有用過都是正常的

是不是一開始驗證碼加載比較慢的關係

**Comment by max32002** [comment]
這個問題，我要在下次大型活動搶票時，才能做測試，"暫時"先使用我的想像力來模擬可能的狀況，已經在 2023-02-05 版本，增加一個錯誤時重試的機制，不確定是否能解決這個問題。

**Comment by max32002** [comment]
hello, 這個問題發生的4個月前, 我猜, 應該是解決了, 如果還有遇到問題, 請開新的issue. 謝謝. 
附註:  arm CPU 暫時不支援驗證碼自動輸入, 因為我使用的元件是  ddddocr, 可以 google 這個關鍵字看看.
