### ISSUE TITLE
拓元搶票異常

### ISSUE THREAD

**Issue by F88F59** [max32002/tixcraft_bot#261]
請問圖片問題該如何解決? 非售票日系統無法正常搶票? 感謝     Max大加油!!!

![ERROR](https://github.com/max32002/tixcraft_bot/assets/172627443/a8f3ce61-af95-42b7-a923-f7388c9fb7b2)

**Comment by max32002** [comment]
你帳號沒登入吧，請用 SID.

**Comment by F88F59** [comment]
忘記獲取新鮮的SID，感謝Max大
