### ISSUE TITLE
0408版本ibon無法選擇付款方式

### ISSUE THREAD

**Issue by KennyHsu91** [max32002/tixcraft_bot#264]
0408版本在ibon選到票之後進入選擇付款方式時會直接下一步
無法選擇付款方式

**Comment by KennyHsu91** [comment]
看完這篇了解了
https://github.com/max32002/tixcraft_bot/issues/222

**Comment by max32002** [comment]
如果還有需要協助的地方，請再 reopen issue 或 開新的 issue.
