### ISSUE TITLE
cityline的cloudflare檢測好像不能通過了

### ISSUE THREAD

**Issue by tungzip** [max32002/tixcraft_bot#266]
![微信截图_20240625232832](https://github.com/max32002/tixcraft_bot/assets/41478294/fc148deb-20e1-4786-981d-4e544f240ab4)

**Comment by max32002** [comment]
2024-06-26, 09:00AM 測試結果，成功。
<img width="612" alt="Screenshot 2024-06-26 at 8 59 55 AM" src="https://github.com/max32002/tixcraft_bot/assets/4498233/8e6f0abe-ffe9-4f0e-8d1e-e43cde2cde97">

**Comment by max32002** [comment]
你可能是使用到舊的版本，webdriver 設定為 uc, 請改用 MaxBot (2024.04.19)，會自動地，遇到cityline 把 webdriver 切換為 nodriver.
