### ISSUE TITLE
CItyline 正式開賣時建議程式可以自動點選「按此購票」按鈕

### ISSUE THREAD

**Issue by aphwong** [max32002/tixcraft_bot#27]
平台： CityLine

考慮到多開的情況
如果活動一開賣
需要手動點選「按此購票」才動進入活動頁面
會做不到所有多開視窗
第一時間同時進入活動頁面 (因每個視窗也要手動點選一次「按此購票」)
能用爬蟲把這個按鈕也自動按嗎？

### **_活動倒數中_**
![image](https://user-images.githubusercontent.com/43560054/216880193-ae73609f-1080-4660-af69-1117b4270f85.png)
### **_活動倒數完畢 (程式現時不會自動點選「按此購票」)_**
![image](https://user-images.githubusercontent.com/43560054/216880223-7ee51949-8ee0-4a06-b4b3-d95a15d35dea.png)

**Comment by max32002** [comment]
please download 2023-02-05 version.
demo video: https://youtu.be/BVl4a2jOI-k

**Comment by aphwong** [comment]
> please download 2023-02-05 version.
> demo video: https://youtu.be/BVl4a2jOI-k

影片權限能開放嗎？
感謝MAX大

**Comment by max32002** [comment]
WOW, 你觀看的速度，比我上傳還快。
