### ISSUE TITLE
遠大無法正常搶票

### ISSUE THREAD

**Issue by goddessnpust** [max32002/tixcraft_bot#273]
因遠大將購票頁面的驗證碼移除了
故程式在購票過程中會因為找不到驗證碼輸入處而卡住

**Comment by max32002** [comment]
請問,您使用的版本

gdnpust ***@***.***> 於 2024年7月18日 週四 下午11:25 寫道：

**Comment by goddessnpust** [comment]
剛剛換成最新0421版本發現可以了
不好意思勞煩您了

**Comment by max32002** [comment]
👍

gdnpust ***@***.***> 於 2024年7月18日 週四 下午11:31 寫道：
