### ISSUE TITLE
如何在kktix使用會員優先購票

### ISSUE THREAD

**Issue by shawn0309** [max32002/tixcraft_bot#274]
如題，是否能像您之前在拓元系統示範"信用卡號認證"的影片一樣，輸入會員認證碼即可

**Comment by max32002** [comment]
應該是和拓元同一個輸入框。

但實際上，kktix 密碼輸入的網頁上的格式有好幾個，所以不確定是否能自動輸入設定的文字。

shawn0309 ***@***.***> 於 2024年7月21日 週日 上午12:45 寫道：

**Comment by max32002** [comment]
有機會自動輸入。取決於是否為之前遇到過的網頁語法的格式，翻譯為白話文：取決於MaxBot的腳本以前是否有處理過。

如果有遇到沒辦法輸入的場次，請再提供可以複製出問題的 url, 謝謝。
