### ISSUE TITLE
KKTIX會員預購

### ISSUE THREAD

**Issue by ChuangJui** [max32002/tixcraft_bot#276]
想請問是否有支援KKTIX的會員預購自動輸入會員帳號，謝謝。

**Comment by max32002** [comment]
有機會自動輸入。取決於是否為之前遇到過的網頁語法的格式，翻譯為白話文：取決於MaxBot的腳本以前是否有處理過。

如果有遇到沒辦法輸入的場次，請再提供可以複製出問題的 url, 謝謝。
