### ISSUE TITLE
M3 Mac執行原始碼到第三步驟

### ISSUE THREAD

**Issue by hidindin** [max32002/tixcraft_bot#277]
您好，想請問Mac M3系列的電腦
執行到第三步驟安裝套件時，出現這個錯誤
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'pip-req.txt'

這樣要怎麼處理？

**Comment by max32002** [comment]
已改檔名，參考網頁說明。

YouTube 影片下方也有加註說明。

hidindin ***@***.***> 於 2024年7月24日 週三 下午6:53 寫道：

**Comment by hidindin** [comment]
@max32002  謝謝您的回覆，已經可以使用了，不過剛用ibon測試，發現設定只購買一張，但頁面會自動一直刷新直到訂滿四張，請問這個問題該如何解決呢？謝謝！

**Comment by max32002** [comment]
小問題，暫停maxbot, 再回去ibon 刪除較遠座位即可。

hidindin ***@***.***> 於 2024年7月24日 週三 下午9:51 寫道：
