### ISSUE TITLE
Ticketmaster SG 提交驗證碼表單後Google Chrome無響應

### ISSUE THREAD

**Issue by yupeijia20010404** [max32002/tixcraft_bot#279]
您好，首先非常感謝分享source code！我使用bot在ticketmaster sg網站購票時，在提交驗證碼表單後遇到Google Chrome無法響應的問題（圖一），終端報錯“find toast element fail"（圖二），最後強制關機時Google瀏覽器仍無響應（圖三）。請問原因是我的電腦配置不夠嗎？
我的電腦配置：MacBook Pro 13-inch 2020，處理器 2GHz 4 Intel Core i5，圖形卡 Intel Iris Plus Graphics 1536 MB，內存 16 GB 3733 MHz LPDDR4X，操作系統 macOS 14.5 (23F79)
我使用bot的操作：
1、輸入預售鏈接，點擊搶票，Google Chrome自動打開livenation sg預售網站
2、點擊預售網站的按鈕直接進入ticketmaster sg的“Buy Tickets"按鈕界面
3、bot自動幫我選區和張數，提交第一個表單後自動到填寫驗證碼的界面
4、在填好驗證碼提交時，無論驗證碼是否正確都會導致瀏覽器卡死
<img width="1013" alt="截屏2024-07-30 上午10 27 57" src="https://github.com/user-attachments/assets/5aa6e9f7-944a-4fd9-acbe-29d6a7dbb389">
<img width="568" alt="截屏2024-07-30 上午10 28 35" src="https://github.com/user-attachments/assets/236c7a95-577c-49f7-b5ba-361c133add97">
<img width="476" alt="截屏2024-07-30 上午10 30 36" src="https://github.com/user-attachments/assets/f260732f-76ca-462c-ae3a-a8a080179194">

**Comment by max32002** [comment]
1: 請改用 2024-04-22 版，看看還會不會遇到這個問題，我猜應該還是會，我先關掉這個 issue, 等你複製出問題，再重啟，並建議您，只需要反白並複製黑黑視窗裡的文字訊息，會比截圖提供更多的訊息。

2: 2020 的電腦，應該不會太慢，但「搶票」是比快，有空的話，借一台 Windows 電腦看看同一個場次的 ticketmaster.sg 購票時間，那一個平台花的比較多，購票花費多少時間，會顯示在黑黑的那個視窗。

**Comment by yupeijia20010404** [comment]
感謝您的回覆，我能夠下載的最新版本是2024-04-21發布的，並且是latest branch，請問可以申請2024-04-22 版的下載權限嗎？另外您說需要複製的文字信息，指的是終端的所有輸出（比如像我中間放的那張截圖）？謝謝！
我使用的2024-04-21版目前會在ticketmaster sg的提交驗證碼頁面出錯，所以暫時還未能輸出購票成功的消息以及購票所花費的時間。
