### ISSUE TITLE
Urbtix blocked

### ISSUE THREAD

**Issue by Steventam112** [max32002/tixcraft_bot#29]
I think it's the undetected_chromedriver problem.
I found out by accident that version 3.1.5.post4 worked but not 3.4.6 was blocked.
I did not try the other version yet.

**Comment by max32002** [comment]
哇！你好專業哦！

Steventam112 ***@***.***> 於 2023年2月17日 週五 下午1:51 寫道：

**Comment by max32002** [comment]
先關閉這個issue, 歡迎再開新的issue 來反應.
