### ISSUE TITLE
功能請求: 在 Facebook 自動填入密碼

### ISSUE THREAD

**Issue by flizzy420** [max32002/tixcraft_bot#30]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/52878239/219686118-e1b0c951-adf0-47db-a0b6-482a1222ff6d.png">

密碼 input:

> selector
> `#u_0_e_F2 > div > div.phl.ptm.uiInterstitialContent > table > tbody > tr._3stt > td > input[type=password]`
> xpath
> `//*[@id="u_0_e_F2"]/div/div[2]/table/tbody/tr[1]/td/input`

繼續 input:

> selector
> `#u_0_0_6L`
> xpath
> `//*[@id="u_0_0_6L"]`

感謝 Max 大提供的程式。

**Comment by max32002** [comment]
哇！真酷，你。

Flizzy ***@***.***> 於 2023年2月17日 週五 下午10:50 寫道：
