### ISSUE TITLE
Google 無法登入

### ISSUE THREAD

**Issue by WuTank** [max32002/tixcraft_bot#32]
![image](https://user-images.githubusercontent.com/38752731/220244401-438462a7-e27c-49c3-a60c-c18d24e46ba3.png)
程式開啟的Chrome 無法Google登入，一般開啟Chrome 是可以正常登入的

**Comment by max32002** [comment]
已有相同議題, 請參考:
https://github.com/max32002/tixcraft_bot/issues/3
