### ISSUE TITLE
KKTIX票券張數無法設定

### ISSUE THREAD

**Issue by ytl0623** [max32002/tixcraft_bot#35]
...
https://kktix.com/events/spaceport2023-01/registrations/new
registerStatus: IN_STOCK
asssign ticket number:2
asssign ticket number to ticket-price field Exception:
Message: element not interactable
  (Session info: chrome=110.0.5481.104)
Stacktrace:
Backtrace:
        (No symbol) [0x009A37D3]
        (No symbol) [0x00938B81]
        (No symbol) [0x0083B230]
        (No symbol) [0x00868586]
        (No symbol) [0x008676A7]
        (No symbol) [0x0088B41C]
        (No symbol) [0x00862B96]
        (No symbol) [0x0088B774]
        (No symbol) [0x008A1215]
        (No symbol) [0x0088B216]
        (No symbol) [0x00860D97]
        (No symbol) [0x0086253D]
        GetHandleVerifier [0x00C1ABF2+2510930]
        GetHandleVerifier [0x00C48EC1+2700065]
        GetHandleVerifier [0x00C4C86C+2714828]
        GetHandleVerifier [0x00A53480+645344]
        (No symbol) [0x00940FD2]
        (No symbol) [0x00946C68]
        (No symbol) [0x00946D4B]
        (No symbol) [0x00950D6B]
        BaseThreadInitThunk [0x76A100F9+25]
        RtlGetAppContainerNamedObjectPath [0x77717BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77717B8E+238]

**Comment by max32002** [comment]
我測試，這一場次，功能都正常：

https://kktix.com/
https://kktix.com/events/spaceport2023-01/registrations/new
registerStatus: IN_STOCK
find person_agree_terms checkbox fail, do refresh page.
try to refresh page...
registerStatus: IN_STOCK
asssign ticket number:2
wait form-actions div wait to be clickable Exception:
Message: 

https://kktix.com/events/spaceport2023-01/registrations/130156272-fc9be919812ef37728f911d3b689b45b
https://kktix.com/events/spaceport2023-01/registrations/130156272-fc9be919812ef37728f911d3b689b45b#/

**Comment by ytl0623** [comment]
Sorry, it's my fault.

Thank you, Max.
