### ISSUE TITLE
拓元更新後頁面不會重複刷新

### ISSUE THREAD

**Issue by alwww7** [max32002/tixcraft_bot#37]
最近使用最新版的程式發現在尚未開賣的頁面不會再自動刷新，已確定有開啟「自動刷新倒數中的日期頁面」
另外使用舊版程式測試是會自動刷新的

**Comment by max32002** [comment]
hello, 不知道你說的是那一個場次，我更新程式到 2023-02-27, 請你有空再測試看看：
https://github.com/max32002/tixcraft_bot/commit/a027410b28aa7417bb35290c1dcddb74ca3e15f9

**Comment by alwww7** [comment]
下載最新版已經沒問題了，感謝
