### ISSUE TITLE
能否增加手動暫停功能?

### ISSUE THREAD

**Issue by Jackwong01** [max32002/tixcraft_bot#39]
以昨天black pink澳門公售為例，
https://ticketing.galaxymacau.com/shows/show.aspx?sh=BPBPWT23

Maxbot成功retry 進入購票網頁，但由於當時系統繁忙，進入網頁後大約幾秒後才出現ticket 的elements,  導致bot不斷refresh網頁嘗試尋找ticket 的elements。重複幾分鐘後，關閉bot後才能正常運作。

假如將來的更新，能否加入手動暫停的功能? 因為搶票時server流量大，bot未必能正常運作。

在此先感謝一直的更新。🙏

**Comment by max32002** [comment]
已加入新功能到  2023-03-11 版本中。
<img width="622" alt="Screen Shot 2023-03-13 at 1 30 26 AM" src="https://user-images.githubusercontent.com/4498233/224562201-194a58ba-6fb0-4543-97e1-5ac03fb88dcf.png">
