### ISSUE TITLE
希望能增加min票數量

### ISSUE THREAD

**Issue by Uly41** [max32002/tixcraft_bot#4]
有時候搶演唱會都是跟親友們一起去
設定最大值2或4時，時常會跑進只有1張票的區域
導致需要重來，重來又可能又跑進1張票的區域，無限loop，錯失搶票黃金期

希望大大能增加min設定，判斷小於min數的就pass

**Comment by max32002** [comment]
![Screen Shot 2021-03-21 at 14 12 08](https://user-images.githubusercontent.com/4498233/111896010-98794300-8a51-11eb-8cef-64310e15a621.png)
試看看這一個 2020-03-21 release:
https://github.com/max32002/tixcraft_bot/commit/28c00c4ca3579f8d4e4c0a9cb5d92e7c7f24350c

**Comment by Uly41** [comment]
希望win64版釋出~~~~

**Comment by max32002** [comment]
> 希望win64版釋出~~~~

已更新。

**Comment by Uly41** [comment]
max大，回報一下情況，全場如只有一個區域且只剩一個位子時，會停止refresh page

**Comment by max32002** [comment]
> max大，回報一下情況，全場如只有一個區域且只剩一個位子時，會停止refresh page

針對這一個情況，調整程式為 2021-03-22 版本，由於沒有找到場次做測試，不確定是不是會造成「其他」的新問題。
