### ISSUE TITLE
ibon在驗證問題填寫答案不能使用

### ISSUE THREAD

**Issue by alwww7** [max32002/tixcraft_bot#41]
使用ibon系統搶票，在setting頁面中有設定好在驗證問題填寫答案，但實際搶票時卻不會自動輸入

**Comment by max32002** [comment]
因為沒有去寫過，已加入功能到 2023-03-11, 如果使用後還有問題，請再發issue.

異動到程式碼如下：https://github.com/max32002/tixcraft_bot/commit/316fc727d8c7e18769ee3ecbb9555ae4173a24d0

**Comment by alwww7** [comment]
非常感謝，下次有題目的搶票再來試看看。另外昨天有截圖ibon搶票時出現題目的頁面但忘記附上了，在這邊補上不知道有沒有幫助
![messageImage_1678593188668](https://user-images.githubusercontent.com/126540775/224588833-9de47c3f-5601-4a8e-82e2-85d0d5d47331.jpg)
