### ISSUE TITLE
ibon有題目的話 機器人就不會動了

### ISSUE THREAD

**Issue by c654321000** [max32002/tixcraft_bot#43]
ibon有題目的話 機器人就不會動了

請問有辦法解決嗎?

**Comment by max32002** [comment]
已解決, 參考影片:
Max搶票機器人2023-06-18：KKTIX/ibon/拓元 合併本地字典與線上字典檔
https://youtu.be/LnJbZokIyOY

Max搶票機器人2023-06-17：ibon 檢示與輸入驗證問題與答案/線上JSON代管
https://youtu.be/ues16dHB7UI
