### ISSUE TITLE
Ibon 無法搶票會自動跳到主頁面

### ISSUE THREAD

**Issue by logan0812** [max32002/tixcraft_bot#44]
Ibon 系統使用機器人搶票後，會閃退到主畫面。但一陣子後也會恢復正常。

**Comment by ytl0623** [comment]
+1, 遇到相同狀況！
![image](https://user-images.githubusercontent.com/55120101/227753034-cc0c1c8a-da28-41ac-be92-ea3f717db3ec.png)

**Comment by max32002** [comment]
請改用2023-03-22版。

ytl0623 ***@***.***> 於 2023年3月26日 週日 上午11:08 寫道：

**Comment by ytl0623** [comment]
Hi, Max, I got this error in the latest(2023-03-22) version.
![image](https://user-images.githubusercontent.com/55120101/227753309-09fe608c-5d5e-43b8-aa8d-664dee03e1e8.png)

**Comment by ytl0623** [comment]
OK, I got it. Add a ":" end of line.

**Comment by max32002** [comment]
please download or pull again, I have fixed this bug.
ytl0623 ***@***.***> 於 2023年3月26日 週日 上午11:19 寫道：

**Comment by max32002** [comment]
已解決, 參考影片:
Max搶票機器人2023-06-18：KKTIX/ibon/拓元 合併本地字典與線上字典檔
https://youtu.be/LnJbZokIyOY

Max搶票機器人2023-06-17：ibon 檢示與輸入驗證問題與答案/線上JSON代管
https://youtu.be/ues16dHB7UI

如果還有問題, 歡迎開新issue.
