### ISSUE TITLE
Ibon在驗證中填寫此答案無法自動送出

### ISSUE THREAD

**Issue by logan0812** [max32002/tixcraft_bot#45]
想詢問使用2023-03-20版本，ibon 系統在使用【驗證中填寫此答案】功能後，無法自動送出。

**Comment by alwww7** [comment]
今天也遇到這個問題，有試過在驗證問題中填寫多組答案，答案中的分隔符號功能也正常，但每次輸入不同答案後不會送出，只會繼續換下一個答案

**Comment by max32002** [comment]
已解決, 參考影片:
Max搶票機器人2023-06-18：KKTIX/ibon/拓元 合併本地字典與線上字典檔
https://youtu.be/LnJbZokIyOY

Max搶票機器人2023-06-17：ibon 檢示與輸入驗證問題與答案/線上JSON代管
https://youtu.be/ues16dHB7UI
