### ISSUE TITLE
Urbtix重复刷新进不去页面

### ISSUE THREAD

**Issue by Deeyou0424** [max32002/tixcraft_bot#46]

**Comment by max32002** [comment]
你只要拿出手機,  連到這個網址, 就會發現不使用機器人也進不去urbtix.
https://www.urbtix.hk/

**Comment by PeterMtCheung** [comment]
> 你只要拿出手機, 連到這個網址, 就會發現不使用機器人也進不去urbtix. https://www.urbtix.hk/

手機能進, 不用機器人開的browser也能進, 但用機器人開的browser就不能進了

**Comment by max32002** [comment]
> > 你只要拿出手機, 連到這個網址, 就會發現不使用機器人也進不去urbtix. https://www.urbtix.hk/
> 
> 手機能進, 不用機器人開的browser也能進, 但用機器人開的browser就不能進了

那，就是，被檢測到了，無法使用搶票程式。

**Comment by max32002** [comment]
如果還有遇到問題, 請再開issue.
