### ISSUE TITLE
開發程式

### ISSUE THREAD

**Issue by a3504411** [max32002/tixcraft_bot#48]
max32002 您好

最近看到您的搶票程式，覺得很有趣，想自行學習開發
想從trace code開始，所以想問全部的功能都在這包source code裡面麻
這方面的開發有推薦的書籍麻，謝謝。

**Comment by max32002** [comment]
加油，也許吧。

Jacky Lin ***@***.***> 於 2023年3月28日 週二 下午3:41 寫道：

**Comment by max32002** [comment]
沒有推薦的書, 因為我沒看過書, 都是問Google 的, 歡迎再開新的issue,  這個先關了. 

我有順便把google 的過程寫到筆記裡, 方便下次再翻會比較容易找到:
https://stackoverflow.max-everyday.com/category/python/
