### ISSUE TITLE
開發問題

### ISSUE THREAD

**Issue by PeterMtCheung** [max32002/tixcraft_bot#49]
請問怎樣在開賣前或平日獲得排隊的連結用作開發?

**Comment by max32002** [comment]
1: 先會學程式開發的技能.
2: 去你想要排隊的公司應徵.
3: 去認識開發的團隊, 就可以打聽到排隊的連結用開發.

**Comment by max32002** [comment]
這個問題, 似乎暫時無解, 先關掉, 歡迎再開新的 issue.
