### ISSUE TITLE
請問這個bot支持hkticketing.com嗎

### ISSUE THREAD

**Issue by mrr010** [max32002/tixcraft_bot#5]
謝謝~~

**Comment by max32002** [comment]
目前沒有，不好意思。

mrr010 ***@***.***> 於 2021年5月11日 週二 下午5:33 寫道：

**Comment by max32002** [comment]
因為Google 的 reCaptcha 檢測到正在使用機器人，所以目前暫時要先跟快達票說bye-bye, 等機器人可以避開被 reCaptcha 檢測到之後，再回來支援。

**Comment by max32002** [comment]
hkticketing.com 前陣子有支援. 先關掉這個issue, 有問題, 歡迎再開新issue.
