### ISSUE TITLE
請問chrome 拓元sid 取得方式是否改變?

### ISSUE THREAD

**Issue by hhderic** [max32002/tixcraft_bot#50]
你好，先前有看到影片知道要按鎖頭〉cookie，但現在跳出來視窗不一樣了，需要改變甚麼方式來取得sid呢? 別的瀏覽器(fire fox)也可以這樣取得嗎?

謝謝回覆

**Comment by max32002** [comment]
在 Windows 請按 F12 或 Ctrl + Shift + I, 在 macOS 請按 Cmd+Option+I, 即可叫出開發者工具(DevTools)，在畫面的 Appliction 分頁裡的 Storage 項目中的 Cookies 裡即取得拓元登入後的 SID值：
![Screen Shot 2023-04-08 at 12 17 52 PM](https://user-images.githubusercontent.com/4498233/230702930-d900c81e-4308-4fee-a4e3-81da74fab115.png)

詳細的討論串，合併到：
https://github.com/max32002/tixcraft_bot/issues/3

**Comment by hhderic** [comment]
了解了！謝謝回覆！
