### ISSUE TITLE
Ticketplus 會卡在選擇票區的頁面

### ISSUE THREAD

**Issue by az25256058** [max32002/tixcraft_bot#51]
OS：Win 10 21H2
Chrome Version：112.0.5615.50 (正式版本) (64 位元)
Bot Version：chrome_tixcraft.20230331

實測ticket plus網站
會卡在選擇票區的頁面
執行的視窗會不斷跳這幾行訊息 (某些tag沒抓到?)

select all captcha text
find ticket_number_div fail
start to ddddocr
ddddocr is None
ocr_answer is None
previous_answer: None

有打算維護這塊嗎?
謝謝

**Comment by liaojack8** [comment]
@az25256058 `ddddocr`是驗證碼辨識的問題, 關掉自動辨識的話應是正常的

**Comment by max32002** [comment]
這個問題，目前的版本應該是已解決了一部份。

還沒解決的是ddddocr 並沒有訓練到ticket plus 的這種風格的驗證碼，目前還沒有找到適合的，準確率高的OCR 元件。

結論，暫不支援推論驗證碼。

EiC ***@***.***> 於 2023年4月20日 週四 上午12:21 寫道：

**Comment by max32002** [comment]
應該是解決了, 有遇到問題的話, 請再開新issue. 參考看看影片:
2023-06-28:遠大自動登入帳號
* 檢查票數是否正確. 
* 微調驗證碼的重設.
https://youtu.be/PJS_BILjErQ
