### ISSUE TITLE
Kktix自動猜題卡住

### ISSUE THREAD

**Issue by logan0812** [max32002/tixcraft_bot#52]
4/9使用03/31版本的搶票機器人進行kktix系統搶票，因此場活動有設置考題，所以機器人也開始自動猜測答案，不過才自動猜測第一個選項，網頁就整個卡死了！也沒有再猜測下一個選項了，但先前測試其它場活動，都可以順利依序自動猜測所有選項。但正式開賣場次只會猜測第一個選項就會卡死。

**Comment by max32002** [comment]
試看看這個解法:
https://youtu.be/etT6Nr9a-_M
