### ISSUE TITLE
不管有沒有勾選 Pass date is sold out, 選購一空的頁面一直 refresh

### ISSUE THREAD

**Issue by ntubrian** [max32002/tixcraft_bot#53]
執行環境 Mac OS 本機 run the command 
python3 settings.py

**Comment by max32002** [comment]
請問, 是那一個售票平台的那一個活動? 

當票都賣完時, 是會一直 refresh, 直接官方釋票為止.

**Comment by ntubrian** [comment]
> 請問, 是那一個售票平台的那一個活動?
> 
> 當票都賣完時, 是會一直 refresh, 直接官方釋票為止.

拓元的平台
https://tixcraft.com/activity/game/23_more2come

我原本預期把該選項tick 掉就不會一直 refresh

**Comment by max32002** [comment]
在按"搶票"按鈕後所修改的設定值, 對已開出的視窗來說目前是無法被套用, 是使用按搶票前的設定值.

**Comment by max32002** [comment]
先假設問題已解決. 如果還有遇到會"一直 refresh"的問題, 請再開新issue, 附上您的設定值, 與測試用的場次資訊, 謝謝.
