### ISSUE TITLE
buster擴充無法使用

### ISSUE THREAD

**Issue by logan0812** [max32002/tixcraft_bot#55]
2023-04-17版本增加的buster擴充無法使用，點了小黃人後，會顯示Try again later，想問是需要在擴充頁面付款才能使用此功能嗎。

**Comment by max32002** [comment]
小黃人，不一定每次都成功。


logan0812 ***@***.***> 於 2023年5月1日 週一 上午7:39 寫道：

**Comment by max32002** [comment]
reCaptcha 的問題目前無解, 只能挑戰並希望在同時間, 大量且多人在搶票時, reCaptcha 會沒動作.

**Comment by max32002** [comment]
無解, 跳過...
