### ISSUE TITLE
Kktix無法自動選張數

### ISSUE THREAD

**Issue by lisachen0515** [max32002/tixcraft_bot#58]
近期測試4/24版本的搶票機器人搶最近每場kktix的演唱會，有提前設置區域關鍵字，但在整點進入搶票當下，不會自動選擇張數，只會一直重新整理。但過一陣子就可以自動選擇張數了，這種情況有方法解決嗎。

**Comment by chuanxd** [comment]
似乎選擇張數超過 1 張就會有這情況發生

**Comment by max32002** [comment]
請問, 使用新的版本,還會遇到這個問題嗎?

**Comment by max32002** [comment]
Hello, 我先關閉這個issue, 如果還有遇到, 可以再回來 Reopen issue 或是開新 issue, 如果還可以遇到, 請附上測試用的場次, 還有搶票機器人的設定值, 最好還可以附上黑色的視窗裡的訊息們. 

附註: kktix 有 reCaptcha 圖示的場次, 搶票程式會掛掉是正常的... , 這個目前無解.
