### ISSUE TITLE
新人有疑問

### ISSUE THREAD

**Issue by f0530y** [max32002/tixcraft_bot#6]
請問 為什麼用古哥瀏覽器  無法登入進拓元 請問我是不是有什麼步驟弄錯

**Comment by max32002** [comment]
參考網頁說明。

f0530y ***@***.***> 於 2021年11月20日 週六 下午8:49 寫道：

**Comment by f0530y** [comment]
> 請問 為什麼用古哥瀏覽器  無法登入進拓元 請問我是不是有什麼步驟弄錯

**Comment by max32002** [comment]
合併問題到： https://github.com/max32002/tixcraft_bot/issues/3
