### ISSUE TITLE
ibon遇到不需要選位的場次會卡住

### ISSUE THREAD

**Issue by alwww7** [max32002/tixcraft_bot#61]
ibon網站售票，若遇到不需要選位置的場次，進去後是直接選擇張數，則程式會無法順利執行選擇張數及輸入驗證碼
例如高雄啤酒音樂節(https://ticket.ibon.com.tw/ActivityInfo/Details/37754)

**Comment by max32002** [comment]
改好了 2023-05-19 版, 我先關閉, 測到問題的話, 再重開 issue.
