### ISSUE TITLE
Ibon 宇宙人沒辦法填寫驗證碼

### ISSUE THREAD

**Issue by hkaiiiii** [max32002/tixcraft_bot#62]
如題

**Comment by hkaiiiii** [comment]
重複刷新頁面 沒辦法輸入驗證嗎

**Comment by max32002** [comment]
票都賣完了，沒法測。

hkaiiiii ***@***.***> 於 2023年5月20日 週六 下午12:24 寫道：

**Comment by max32002** [comment]
改好了 2023-05-19 版,  我先關閉, 測到問題的話, 再重開 issue.
