### ISSUE TITLE
自動選完張數後，最後游標會停在張數欄位，不會自動點選驗證碼框框，導致我們必須多按一個Tab鍵

### ISSUE THREAD

**Issue by Jonas911008** [max32002/tixcraft_bot#64]

**Comment by max32002** [comment]
請問, 是那一個售票系統? 使用新的版本, 還有這個問題嗎?

**Comment by Jonas911008** [comment]
拓元和KK都有這情況，最新版本還是有問題

**Comment by LeoLiu1209** [comment]
@Jonas911008 想詢問你在拓元遇到的情況是 "啟用猜測驗證碼" 沒有打勾的狀況下嗎?

**Comment by Jonas911008** [comment]
對沒錯，沒有啟用自動驗證碼時

**Comment by max32002** [comment]
有空請再幫忙用 2023-06-24 版,試看看.

**Comment by LeoLiu1209** [comment]
我在KKTIX都沒有出現打驗證碼的環節，所以我沒辦法reproduce KKTIX的狀況，https://github.com/max32002/tixcraft_bot/pull/77 只修了tixcraft的部分.
