### ISSUE TITLE
ibon若遇到該區域賣完無法自動重新整理

### ISSUE THREAD

**Issue by alwww7** [max32002/tixcraft_bot#67]
假設我在設定內區域關鍵字只打上"A2"，若A2目前顯示已售完，則不會重新整理頁面，程式碼會一直跑出find verify code fail，如下圖
![image](https://github.com/max32002/tixcraft_bot/assets/126540775/f07726f3-b44e-40a1-814a-1a2388e8cc24)

**Comment by max32002** [comment]
測試, 區域關鍵字 A8, 刷下面這場, 使用 2023-05-27 版, 是會重新整理. 
https://orders.ibon.com.tw/application/UTK02/UTK0201_000.aspx?PERFORMANCE_ID=B05336UG&PRODUCT_ID=B0530Z8O
![2023-06-02 21_48_44-MaxBot (2023 05 27)](https://github.com/max32002/tixcraft_bot/assets/4498233/7a6b21b3-6bcc-45b0-9dfc-ff5ef3a81870)

如果還有測到問題, 請再重啟, 或另開新issue.
