### ISSUE TITLE
ibon若遇到有題目的場次，回答問題後進入選區域頁面無法順利執行

### ISSUE THREAD

**Issue by alwww7** [max32002/tixcraft_bot#68]
測試場次，ibon售票的cravity
在輸入完答案進入售票頁面後，無法自動選擇設定好的區域，需要手動點選區域。
同時若在設定檔中的[在驗證問題中填寫此答案]有設定選項，在驗證問題出現時只會把選項填上去，並不會自動送出答案

**Comment by max32002** [comment]
已解決, 參考影片:
Max搶票機器人2023-06-18：KKTIX/ibon/拓元 合併本地字典與線上字典檔
https://youtu.be/LnJbZokIyOY

Max搶票機器人2023-06-17：ibon 檢示與輸入驗證問題與答案/線上JSON代管
https://youtu.be/ues16dHB7UI
