### ISSUE TITLE
新人疑問

### ISSUE THREAD

**Issue by aser27584** [max32002/tixcraft_bot#7]
在使用最新版本中 for chrome 96 ,要登入拓元的會員 使用google的帳戶登入
最後都會顯示
目前無法登入帳戶
這個瀏覽器或應用程式可能有安全疑慮。
建議您改用其他瀏覽器。如果您目前已使用系統支援的瀏覽器，可以再試著登入帳戶。
所以是被google的安全性擋在門外嗎?有辦法解嗎?

**Comment by max32002** [comment]
雖然是已知問題，暫時還沒有去解決，請參考網頁上的說明。

aser27584 ***@***.***> 於 2021年11月27日 週六 上午7:58 寫道：

**Comment by max32002** [comment]
相關討論， 合併到 https://github.com/max32002/tixcraft_bot/issues/3
