### ISSUE TITLE
ticketplus 使用問題

### ISSUE THREAD

**Issue by leo851001** [max32002/tixcraft_bot#70]
欲使用場次
![bug1](https://github.com/max32002/tixcraft_bot/assets/30343874/155bf953-bde5-4bc7-9d88-fc3325dd9f66)

設定
![bug3](https://github.com/max32002/tixcraft_bot/assets/30343874/b15aebc8-2f04-404c-af25-2e191858cc92)

報錯
![bug2](https://github.com/max32002/tixcraft_bot/assets/30343874/f371d75b-6514-49ee-aa30-fa66958b19dd)

說明
看log是找不到下一步的btn
但除此之外在選擇場次的部分也常常選不到
"2樓D區", "5400"
"2樓D區"
"5400"
都嘗試過，就算後面再加 ""
也是會卡住不動

辛苦了!!

**Comment by max32002** [comment]
改用新版本, 試看看. 
2023-06-26:遠大驗證碼自動重試
https://youtu.be/2qC1HBMbAUU
