### ISSUE TITLE
不知道是什么情况,老提示execute .exe binary.

### ISSUE THREAD

**Issue by qiuku1123** [max32002/tixcraft_bot#72]
working_dir: D:\neatdownload\chrome_tixcraft.20230607_ver10_Win10_Win11\chrome_tixcraft
execute in frozen mode
execute .exe binary.

**Comment by max32002** [comment]
過幾個小時後, 下載看看沒有 _Win10_Win11 字樣子的版, 也許就可以使用了.

**Comment by qiuku1123** [comment]
好的，测试了一下其他网站在售门票也是显示这个反馈

Max ***@***.***>于2023年6月7日 周三17:15写道：
