### ISSUE TITLE
mac air m1 arm 開起來黑畫面

### ISSUE THREAD

**Issue by AnselCh** [max32002/tixcraft_bot#73]
mac air m1 arm 開起來黑畫面  
但是按鍵可以按

**Comment by max32002** [comment]
參考：https://max-everyday.com/2018/03/tixcraft-bot/
安裝python3,建議您暫時改用Firefox...

Ansel ***@***.***> 於 2023年6月10日 週六 下午7:00 寫道：

**Comment by AnselCh** [comment]
@max32002 目前是setting的GUI介面打開後會是黑畫面
我有問朋友的m2也是遇到一樣問題
<img width="1007" alt="Screenshot 2023-06-10 at 6 58 06 PM" src="https://github.com/max32002/tixcraft_bot/assets/108506774/7f8a10f3-2614-406c-a79b-5ad846e2e3bf">

**Comment by max32002** [comment]
一樣，請安裝python 3.
參考網頁上的說明。

Ansel ***@***.***> 於 2023年6月11日 週日 下午4:24 寫道：

**Comment by AnselCh** [comment]
刪除py3.9並安裝3.11後沒問題了！
