### ISSUE TITLE
KKTIX 新增驗證防止機器人

### ISSUE THREAD

**Issue by a3504411** [max32002/tixcraft_bot#74]
如題

**Comment by max32002** [comment]
？

Jacky Lin ***@***.***> 於 2023年6月17日 週六 下午1:32 寫道：

**Comment by a3504411** [comment]
https://imgur.com/S6YAsfb

**Comment by max32002** [comment]
Q：KKTIX的演唱會有reCAPTCHA標誌 那這樣適合用搶票機器人搶嗎?
A：reCaptcha 的問題目前無解, 預期機器人應該會被reCaptcha檢測到, 只能希望並挑戰在大量且多人搶票的時候, reCaptcha
會沒動作.

建議您，透過搶票程式多開幾個視窗出來搶，讓程式自動搶票，但你自己開啟原始的(正常的)chrome 來搶票，就可以避開 reCaptcha 。


Jacky Lin ***@***.***> 於 2023年6月17日 週六 下午5:48 寫道：

**Comment by yoin528** [comment]
是不是能使用这个插件增强？
https://cuiqingcai.com/36057.html

**Comment by a3504411** [comment]
有嘗試過，他是自動點擊，如果將點擊速度調快可能會比人工效果還好一點

**Comment by max32002** [comment]
reCAPTCHA 無解, 詳細說明, 參考:
https://max-everyday.com/2018/12/kktix-bot/#recaptcha

**Comment by ALPHAOHR** [comment]
有没有fantopia的程序呢
