### ISSUE TITLE
indievox區域關鍵字功能失效

### ISSUE THREAD

**Issue by Lisachen591002** [max32002/tixcraft_bot#75]
使用最新版本機器人搶indievox售票系統,並提前設定區域關鍵字,搶票執行卻沒有按照設定的關鍵字搶,試了其他版本機器人,區域關鍵字功能也都失效了

**Comment by max32002** [comment]
修改在 2023-06-22 版：
https://github.com/max32002/tixcraft_bot/commit/b12a9abf488038eec5b4a184a3f6b75676ce0744

詳解的用法與說明，參考影片：https://youtu.be/rnYr5CSovGE
