### ISSUE TITLE
Ticketplus 6/26版本會卡在選樓層界面

### ISSUE THREAD

**Issue by Mike1117** [max32002/tixcraft_bot#78]
![977217a84a0fb3661b6639425a6ce52](https://github.com/max32002/tixcraft_bot/assets/86037002/c9841c9e-a0cd-4089-9d6f-1419e2f05d24)

**Comment by max32002** [comment]
2023-06-27:遠大支援第二種購票的網頁框架
https://youtu.be/tveqM0-cmCc
