### ISSUE TITLE
遠大系統自動驗證碼功能問題

### ISSUE THREAD

**Issue by Lisachen591002** [max32002/tixcraft_bot#79]
使用版本2023.06.27這個版本的搶票機器人搶票，並開啟自動驗證碼功能，但一直驗證錯誤，且自動輸入的驗證碼與圖片完全不一樣

畫面如下，
![7C595A49-E7B3-438A-A917-DD86E39EA6DB](https://github.com/max32002/tixcraft_bot/assets/132981011/32439f97-cdd2-4473-bd5d-9badcae9a393)
![EA6DE4EC-8CDB-43F6-AAAB-3E9685795AA9](https://github.com/max32002/tixcraft_bot/assets/132981011/6bbf13ac-d540-4f26-8a12-d9ddc37e59fe)

**Comment by max32002** [comment]
你的截圖來看, 官方是  szlg, ocr 推測結果為 3zlg, 幾乎算是正確, 因為這個準確率, 本來就不高. 

2023-06-28:遠大自動登入帳號
* 檢查票數是否正確. 
* 微調驗證碼的重設.
https://youtu.be/PJS_BILjErQ
