### ISSUE TITLE
城市電腦售票網機器人

### ISSUE THREAD

**Issue by DestinyLam** [max32002/tixcraft_bot#8]
在晚間沒人搶票的時段測試時成功了一次，可是接著下來卻不停卡在重新連接三秒，像是被封掉了，需要換個新的ip還有清掉cookie才可以再次進入購票網站不用再不停三秒重新連接。於其他沒有使用bot的電腦沒有這問題！

所以請問有什麼方法避免使用一次就被封掉的問題嗎？

**Comment by max32002** [comment]
針對會被封IP 的問題, 已增加刷新延遲秒數的功能, 目前沒有"避免使用一次就被封掉"的解決辦法, 怕被封可以增加刷新間隔秒數, 理論上是沒有用, 因為伺服器已非常的忙碌.  

如果還有其他想討論的項目, 歡迎再開新issue.
