### ISSUE TITLE
遠大 門票張數設置問題

### ISSUE THREAD

**Issue by Lisachen591002** [max32002/tixcraft_bot#80]
今天測試2023.6.27版本來搶遠大系統的票，發現提前設置門票張數為2張，但實際卻只有搶一張
![Uploading F5508291-4C38-49FF-9086-C4B7160587B5.jpeg…]()

**Comment by Lisachen591002** [comment]
![Uploading 0F30B396-CCB8-4971-B8A2-AAD16F015675.jpeg…]()

**Comment by max32002** [comment]
2023-06-28:遠大自動登入帳號
* 檢查票數是否正確. 
* 微調驗證碼的重設.
https://youtu.be/PJS_BILjErQ
