### ISSUE TITLE
Mac   ticketmaster.sg會無限刷新

### ISSUE THREAD

**Issue by kentzh1** [max32002/tixcraft_bot#81]
按照建議使用火狐瀏覽器，但是一些演唱會在點擊buy tickets后，会无限刷新，无法进入下一步，关闭bot后手動操作，就沒有問題，這是不是ticketmaster.sg有了應對措施？ 然後bot調用的是基於X86的軟體，是否後期可以優化調用基於ARM架構的瀏覽器軟體？

**Comment by max32002** [comment]
請問，你在ticketmaster 中會無限刷新的場次是那一個？我是使用舊款的INTEL cpu 的 mac 電腦，測試下面的場次，功能大致上都正常:
https://ticketmaster.sg/activity/detail/22_sgartmuseum

**Comment by max32002** [comment]
附註: 使用 Firefox 在 ticketmaster 會被檢測到使用機器人. 必需使用chrome 瀏覽器, 但 arm 電腦上的 chrome browser 會卡卡, 建議借一台 Windows 電腦來使用.

**Comment by max32002** [comment]
如果遇到無限刷新, 請再開新 issue.
