### ISSUE TITLE
ARM處理器的電腦無法自動填寫驗證碼 (拓元或INDIEVOX系統)

### ISSUE THREAD

**Issue by yfes40712** [max32002/tixcraft_bot#82]
使用Mac Ventura 13.4 Chrome瀏覽器 
請問如果無法自動填驗證碼要如何解決？

**Comment by yfes40712** [comment]
不管用edge firefox chrome 都卡在這[](url)
<img width="1172" alt="截圖 2023-07-07 上午7 24 42" src="https://github.com/max32002/tixcraft_bot/assets/138830394/564f2bd1-545f-452e-a87d-eff12e2c1824">

**Comment by max32002** [comment]
Arm CPU 暫時無解, google 看看 ddddocr, 如果有其他 OCR 的解法，也歡迎提供。

**Comment by Ericchen0108** [comment]
Hi @max32002 
我查到這邊說Mac arm是可以使用的
https://github.com/sml2h3/ddddocr/issues/67#issuecomment-1354759005
1，brew install onnxruntime 
2，pip3 intall ddddorc
我自己測試也是可以使用的
是否有辦法改成不偵測你的mac是用arm or x86都可以跑驗證碼呢？

**Comment by max32002** [comment]
> 我自己測試也是可以使用的 是否有辦法改成不偵測你的mac是用arm or x86都可以跑驗證碼呢？

他的解法, 其實是透過 Rosetta, 在 arm CPU上模擬為 intel CPU 環境. 理論上我的 CODE 不需要修改, 只要你的環境可以和他的 script 一樣, 就可以 OCR  成功.

**Comment by AnselCh** [comment]
整理了一下ARM晶片使用ddddorc猜驗證碼的流程
1. 建立環境 這邊使用conda + python3.10
ˋˋˋ
CONDA_SUBDIR=osx-64 conda create -n rosetta python=3.10
ˋˋˋ

2. 切換環境確認切到x86
ˋˋˋ
conda activate rosetta
python -c "import platform;print(platform.machine())"
#x86_64

ˋˋˋ

3. 安裝套件

ˋˋˋ
brew reinstall onnxruntime
pip install chromedriver_autoinstaller
pip install -r pip-req.txt 
ˋˋˋ

4. 執行Ｍax機器人

ˋˋˋ
python3 ./settings.py
ˋˋˋ

PS. Ｍ1 Sonoma 版本14.2.1
使用Brave跑起來最順

**Comment by max32002** [comment]
- [How to run Python as X86 with Rosetta2 on ARM MacOS machine](https://stackoverflow.com/questions/71691598/how-to-run-python-as-x86-with-rosetta2-on-arm-macos-machine)
- If you need to install Rosetta on your Mac
 Rosetta 2 enables a Mac with Apple silicon to use apps built for a Mac with an Intel processor.
 https://support.apple.com/en-us/HT211861
- [如何在 M1 macbook 上安裝 python 環境](https://koding.work/issue-of-install-python-environment-on-m1-macbook/)

**Comment by AlexChang123** [comment]
> 整理了一下ARM晶片使用ddddorc猜驗證碼的流程
> 
> 建立環境 這邊使用conda + python3.10
> 
> ```
> CONDA_SUBDIR=osx-64 conda create -n rosetta python=3.10
> ```
> 
> 切換環境確認切到x86
> 
> ```
> conda activate rosetta
> python -c "import platform;print(platform.machine())"
> #x86_64
> ```
> 
> 安裝套件
> 
> ```
> brew reinstall onnxruntime
> pip install chromedriver_autoinstaller
> pip install -r pip-req.txt
> ```
> 
> 執行Ｍax機器人
> 
> ```
> python3 ./settings.py
> ```
> 
> PS. Ｍ1 Sonoma 版本14.2.1 使用Brave跑起來最順

請問執行後還是出現 No module named 'pyperclip' 請問怎麼解？

**Comment by zjh1943** [comment]
> 整理了一下ARM晶片使用ddddorc猜驗證碼的流程
> 
> 建立環境 這邊使用conda + python3.10
> 
> ```
> CONDA_SUBDIR=osx-64 conda create -n rosetta python=3.10
> ```
> 
> 切換環境確認切到x86
> 
> ```
> conda activate rosetta
> python -c "import platform;print(platform.machine())"
> #x86_64
> ```
> 
> 安裝套件
> 
> ```
> brew reinstall onnxruntime
> pip install chromedriver_autoinstaller
> pip install -r pip-req.txt
> ```
> 
> 執行Ｍax機器人
> 
> ```
> python3 ./settings.py
> ```
> 
> PS. Ｍ1 Sonoma 版本14.2.1 使用Brave跑起來最順

根据这个指导执行完后，执行命令 `python -c "import platform;print(platform.machine())"` 仍然输出 arm64.
