### ISSUE TITLE
ticketmaster.sg 無法訪問

### ISSUE THREAD

**Issue by alanting850420** [max32002/tixcraft_bot#83]
![image](https://github.com/max32002/tixcraft_bot/assets/11245316/389b3241-31e1-47ab-870f-58c697ef69e0)

**Comment by max32002** [comment]
閣下被測出使用BOT, 這很正常, 理論上使用 BOT 應該是可以被檢測的出來. 

請您重開機, 並切換新的 IP address 給電腦, 應該就可以接續使用.

切換新的IP, 可以透過分享手機的熱點.

**Comment by max32002** [comment]
分享 2023-07-14  的執行畫面：
https://youtu.be/Jj2vca2kNZE
