### ISSUE TITLE
在点击“buy tickets”之后页面会一直刷新，编译器显示find verify textbox fail

### ISSUE THREAD

**Issue by Alangreensp4n** [max32002/tixcraft_bot#84]
如下，在出座位图之前会一直刷新，手动暂停运行待选数量的表格出来后继续运行才会向下一步走。偏好里自动刷新日期页面开或关的情况都有试验，都不可以。请问是什么原因呢。在windows上用的chrome

setting app version MaxBot (2023.07.03)
python version 3.9.13
platform Windows-10-10.0.19044-SP0
==[kktix]==
{'auto_press_next_step_button': True, 'auto_fill_ticket_number': True}
==[tixcraft]==
{'date_auto_select': {'enable': True, 'date_keyword': '', 'mode': 'from top to bottom'}, 'pass_date_is_sold_out': True, 'auto_reload_coming_soon_page': False}
==[advanced]==
browser chrome
language 簡体中文
{'play_captcha_sound': {'enable': True, 'filename': 'ding-dong.wav'}, 'tixcraft_sid': '', 'ibonqware': '', 'facebook_account': '', 'kktix_account': '', 'cityline_account': '', 'urbtix_account': '', 'hkticketing_account': '', 'kham_account': '', 'ticketplus_account': '', 'facebook_password': '', 'kktix_password': '', 'cityline_password': '', 'urbtix_password': '', 'hkticketing_password': '', 'kham_password': '', 'ticketplus_password': '', 'adblock_plus_enable': False, 'disable_adjacent_seat': False, 'headless': False, 'verbose': False, 'auto_guess_options': True, 'user_guess_string': '', 'online_dictionary_url': '', 'auto_reload_page_interval': 1.0, 'auto_reload_random_delay': False}
run button pressed.
save config result: True
execute in frozen mode
execute .exe binary.
2023-07-13 19:50:08.2518160 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1827 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
maxbot app version MaxBot (2023.07.03)
python version 3.9.13
platform Windows-10-10.0.19044-SP0
homepage https://ticketmaster.sg
browser chrome
ticket_number 1
pass_1_seat_remaining True
==[kktix]==
{'auto_press_next_step_button': True, 'auto_fill_ticket_number': True}
==[tixcraft]==
{'date_auto_select': {'enable': True, 'date_keyword': '', 'mode': 'from top to bottom'}, 'pass_date_is_sold_out': True, 'auto_reload_coming_soon_page': False}
==[advanced]==
{'play_captcha_sound': {'enable': True, 'filename': 'ding-dong.wav'}, 'tixcraft_sid': '', 'ibonqware': '', 'facebook_account': '', 'kktix_account': '', 'cityline_account': '', 'urbtix_account': '', 'hkticketing_account': '', 'kham_account': '', 'ticketplus_account': '', 'facebook_password': '', 'kktix_password': '', 'cityline_password': '', 'urbtix_password': '', 'hkticketing_password': '', 'kham_password': '', 'ticketplus_password': '', 'adblock_plus_enable': False, 'disable_adjacent_seat': False, 'headless': False, 'verbose': False, 'auto_guess_options': True, 'user_guess_string': '', 'online_dictionary_url': '', 'auto_reload_page_interval': 1.0, 'auto_reload_random_delay': False}
webdriver_type undetected_chromedriver
platform.system().lower(): windows
undetected_chromedriver automatically download chromedriver.
goto url: https://ticketmaster.sg
https://ticketmaster.sg/activity
https://ticketmaster.sg/activity/detail/23_sabrina
redirec to new url: https://ticketmaster.sg/activity/game/23_sabrina
https://ticketmaster.sg/activity/game/23_sabrina
https://ticketmaster.sg/ticket/area/23_sabrina/1079
**find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
is_need_refresh for keyword: CAT1
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
is_need_refresh for keyword: CAT1
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
is_need_refresh for keyword: CAT1
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
is_need_refresh for keyword: CAT1
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
is_need_refresh for keyword: CAT1
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
is_need_refresh for keyword: CAT1
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
is_need_refresh for keyword: CAT1
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
is_need_refresh for keyword: CAT1
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
is_need_refresh for keyword: CAT1
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail
find verify textbox fail**
is_need_refresh for keyword: CAT1
find verify textbox fail
https://ticketmaster.sg/ticket/check-captcha/23_sabrina/1079/2/63
start to ddddocr
ocr elapsed time: 0.057
ocr_answer: ftze
https://main.login.ticketmaster.sg/login?client_id=6vdm5j83n4tc6i0ul4nm9ms6dm&redirect_uri=https%3A%2F%2Fticketmaster.sg%2Flogin&response_type=code&scope=phone+email+openid+aws.cognito.signin.user.admin
NoSuchWindowException at this url:
get_log: Unable to evaluate script: no such window: target window already closed
from unknown error: web view not found

quit bot by NoSuchWindowException

**Comment by max32002** [comment]
請下載 2023-07-04 版.
c78ee2231611845f9013213424d6176c1bf29b07
