### ISSUE TITLE
IBON系統事前輸入驗證問題

### ISSUE THREAD

**Issue by Lisachen591002** [max32002/tixcraft_bot#88]
今日使用7-11版本 搶IBON系統，並事前輸入驗證問題，但執行後，會卡在選擇票價位的區域，不會自動搶進，需要手動點擊，但目前測試只有有問問題的場次才會卡住，其餘場次都會自動搶進。

**Comment by max32002** [comment]
如果可以的話, 請幫我測試 2023-08-01 版, 功能是否正常, 謝謝.

**Comment by max32002** [comment]
請試看看 2023-09-13 之後版本, 看看還會不會出錯, 有問題的話, 再重開 issues.
