### ISSUE TITLE
[Mac M1] Excute settings.py failed

### ISSUE THREAD

**Issue by iita71737** [max32002/tixcraft_bot#89]
Your OpenSource is amazing, you're so great in coding ! 

Thank u for ur OpenSource App a lot

I execute this on my another Intel Macbook is perfect execution. 

I open wrong issue, but I can't close it lol.

**Comment by max32002** [comment]
please install python 3, which is not system build in.
DanLin ***@***.***> 於 2023年8月6日 週日 上午10:49 寫道：

**Comment by max32002** [comment]
welcome to create new issue, if you have new problem.
