### ISSUE TITLE
[遠大] 日期關鍵字容易失效

### ISSUE THREAD

**Issue by iita71737** [max32002/tixcraft_bot#90]
想請問目前日期關鍵字的格式或是輸入規則是什麼？

例如 [這個活動](https://ticketplus.com.tw/activity/3a54c8bd7288a9dad2fccd7e14dc06e3)

有三種活動日期

我最後試只單獨輸入 “2023-08-20"
才有效。

前面試過 "08/20" , "2023/08/20", "2023-08-20(日)" , "" 
以上單獨試與交替試，還有有空字串“”好像都沒效><

**Comment by max32002** [comment]
hello, 請更新為最新版MaxBot 之後, 再試一次看看, 如果還有遇到, 請再開新issue, 並附上您測試的場次, 與使用中的MaxBot 版本, 謝謝.
