### ISSUE TITLE
ibon網站搶票問題

### ISSUE THREAD

**Issue by a22625858** [max32002/tixcraft_bot#91]
如提
上禮拜兩場搶票  疑似因為刷新太快會在開賣那一秒被傳送回首頁
想問有什麼方法可以降低刷新頻率嗎

**Comment by max32002** [comment]
設定界面有一個勾，你勾起來試看看。

a22625858 ***@***.***> 於 2023年8月8日 週二 下午3:38 寫道：

**Comment by a22625858** [comment]
是指刷新延遲那個選項嗎?
那個好像就沒辦法第一時間進去搶票

**Comment by max32002** [comment]
嗯，沒錯。刷太慢搶不到票。
刷太快也有問題。
搶票真難。

a22625858 ***@***.***> 於 2023年8月8日 週二 下午3:45 寫道：

**Comment by a22625858** [comment]
了解謝謝max大
