### ISSUE TITLE
寬宏售票  當日搶票視窗

### ISSUE THREAD

**Issue by a22625858** [max32002/tixcraft_bot#92]
如提
![S__47252692](https://github.com/max32002/tixcraft_bot/assets/141715669/66c68d80-a4cc-483a-afab-b76592476645)
當日搶票寬宏售票  會強制到這個首頁
這裡不會自動刷新 想問max大會這問題能更新嗎?

**Comment by max32002** [comment]
新版, 已解決.
[2023-10-22 release](https://github.com/max32002/tixcraft_bot/releases/tag/20231022)
寬宏增加新的搶票網址.
調整選取區張數檢查的程式碼.
