### ISSUE TITLE
the 403 forbidden issue from tixcraft

### ISSUE THREAD

**Issue by gibson91408** [max32002/tixcraft_bot#96]
While testing the program i test many times for multiple web page (max bot open the goolge drive).
If you open over 2 multiple page (max bot)  in same IP, it will trigger the tixcraft.com 403 forbidden, i was wondering is there have any solution or suggetion?

In my opinion maybe they detect sepecific number of google drive then start counting the refresh page frequency, beacause when i start the max box in two page is fine(no matter how long i execute the max bot).
In three page situation it not return "403 forbidden" immdeately, but go through about few minute then pop out the 403 forbidden. 

![image](https://github.com/max32002/tixcraft_bot/assets/49223935/13f6efc6-aa02-4d59-b155-f44315e085e5)

**Comment by max32002** [comment]
use proxy at second browser, you could add "proxy switch omega" extension to your browser, and  install proxy app on your smart proxy, let compute connect to tixcraft server by your smart phone.

**Comment by max32002** [comment]
you can fix this issue by assign proxy server.

MaxBot 2023-10-10: 支援設定代理伺服器(Proxy)
https://youtu.be/sao9k_PnC0w

示範可以透過設定介面指定Proxy IP:Port, 也可以使用指令的模式指定Proxy.

想挑戰大量連線到搶票伺服器時, 如果搶票伺服器有擋同一 IP 的連線數的時候, 可以透過設定proxy 來解決.

通常很難取得免費、快速且穩定性高的Proxy伺服器, 建議可以多找一些朋友們的手機, 請他們下載proxy伺服器, 透過朋友們的網路來連線, 就只需要付友情成本, 如果沒朋友的話, 就花時間慢慢找免費的Proxy,  或直接花錢買.
