### ISSUE TITLE
IBON輸入驗證問題

### ISSUE THREAD

**Issue by alexwongho** [max32002/tixcraft_bot#98]
如ibon上有兩條驗證問題,應該如何設定兩個答案?

請輸入BOL4 9/30演唱會票券的稅號：(範例：D12345678)
請輸入BOL4 9/30演唱會票券當初購票填寫的手機號碼末三碼：(範例：000)

**Comment by max32002** [comment]
請問, 有可以測試用的場次嗎?

**Comment by max32002** [comment]
請試看看 2023-09-13 之後版本, 看看還會不會出錯, 有問題的話, 再重開 issues.
https://youtu.be/3Yzeu2eftzM
